import { BaseGearAffix } from "./types";

export const BELT_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " (-18--16)% additional damage taken at Low Mana",
    valueRanges: [],
    rawAffix: "` (-18--16)`% additional damage taken at Low Mana",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(386-500)% Critical Strike Rating against Traumatized enemies\n-30% additional Hit Damage",
    valueRanges: [],
    rawAffix:
      "` +(386-500)`% Critical Strike Rating against Traumatized enemies<> ` -30`% additional Hit Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(51-65)% Deterioration Damage",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Deterioration Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +1 Ignite limit\n+5% additional Ignite Damage",
    valueRanges: [],
    rawAffix: "` +1` Ignite limit<> ` +5`% additional Ignite Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Channeled Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Channeled Stacks ` +2` ",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Min Channeled Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Min Channeled Stacks ` +2` ",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " (-15--12)% additional damage taken at Low Mana",
    valueRanges: [],
    rawAffix: "` (-15--12)`% additional damage taken at Low Mana",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(271-385)% Critical Strike Rating against Traumatized enemies\n-30% additional Hit Damage",
    valueRanges: [],
    rawAffix:
      "` +(271-385)`% Critical Strike Rating against Traumatized enemies<> ` -30`% additional Hit Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(36-50)% Deterioration Damage",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Deterioration Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +1 Ignite limit",
    valueRanges: [],
    rawAffix: "` +1` Ignite limit",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Channeled Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Channeled Stacks ` +1` ",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Min Channeled Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Min Channeled Stacks ` +1` ",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(16-20)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(16-20)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(21-26)% Defense",
    valueRanges: [],
    rawAffix: "` +(21-26)`% Defense",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(33-42)% Deterioration Chance",
    valueRanges: [],
    rawAffix: "` +(33-42)`% Deterioration Chance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Dexterity",
    valueRanges: [],
    rawAffix: "` +(61-78)` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Intelligence",
    valueRanges: [],
    rawAffix: "` +(61-78)` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Strength",
    valueRanges: [],
    rawAffix: "` +(61-78)` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Barrage Skills  +(26-32)% damage increase per wave",
    valueRanges: [],
    rawAffix: "Barrage Skills ` +(26-32)`% damage increase per wave",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      "Gains a stack of Fortitude when using a Melee Skill\n(-8--6)% additional damage taken",
    valueRanges: [],
    rawAffix:
      "Gains a stack of Fortitude when using a Melee Skill<> ` (-8--6)`% additional damage taken",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(12-15)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(12-15)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(15-20)% Defense",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Defense",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(23-32)% Deterioration Chance",
    valueRanges: [],
    rawAffix: "` +(23-32)`% Deterioration Chance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Dexterity",
    valueRanges: [],
    rawAffix: "` +(43-60)` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Intelligence",
    valueRanges: [],
    rawAffix: "` +(43-60)` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Strength",
    valueRanges: [],
    rawAffix: "` +(43-60)` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Barrage Skills  +(20-25)% damage increase per wave",
    valueRanges: [],
    rawAffix: "Barrage Skills ` +(20-25)`% damage increase per wave",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      "Gains a stack of Fortitude when using a Melee Skill\n(-5--3)% additional damage taken",
    valueRanges: [],
    rawAffix:
      "Gains a stack of Fortitude when using a Melee Skill<> ` (-5--3)`% additional damage taken",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156) Max Mana",
    valueRanges: [],
    rawAffix: "` +(121-156)` Max Mana",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(221-286) Max Life",
    valueRanges: [],
    rawAffix: "` +(221-286)` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template:
      " +(24-30)% chance for Attacks to inflict Taunt on enemies on hit",
    valueRanges: [],
    rawAffix:
      "` +(24-30)`% chance for Attacks to inflict Taunt on enemies on hit",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(351-455) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(351-455)` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(66-94)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(66-94)`% Minion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(155-220) Max Life",
    valueRanges: [],
    rawAffix: "` +(155-220)` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template:
      " +(17-23)% chance for Attacks to inflict Taunt on enemies on hit",
    valueRanges: [],
    rawAffix:
      "` +(17-23)`% chance for Attacks to inflict Taunt on enemies on hit",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(246-350) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(246-350)` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% Minion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(85-120) Max Mana",
    valueRanges: [],
    rawAffix: "` +(85-120)` Max Mana",
  },
] as const satisfies readonly BaseGearAffix[];

export type BeltPrefixAffix = (typeof BELT_PREFIX_AFFIXES)[number];
