import { BaseGearAffix } from "./types";

export const BELT_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+10Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+110Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+110Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+12Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+140Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+15Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+18Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+35Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+50Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+65Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+80Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+95Max Life",
  },
] as const satisfies readonly BaseGearAffix[];

export type BeltBaseStatsAffix = (typeof BELT_BASE_STATS_AFFIXES)[number];
