import { BaseGearAffix } from "./types";

export const BELT_SWEET_DREAM_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: " +(20-26)% Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(20-26)`% Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: " +(20-26)% Skill Effect Duration",
    valueRanges: [],
    rawAffix: "` +(20-26)`% Skill Effect Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(11-15)% Movement Speed",
    valueRanges: [],
    rawAffix: "` +(11-15)`% Movement Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +(20-25)% chance to launch one more wave when casting a Barrage Skill",
    valueRanges: [],
    rawAffix:
      "` +(20-25)`% chance to launch one more wave when casting a Barrage Skill",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(7-8)% Aura Effect",
    valueRanges: [],
    rawAffix: "` +(7-8)`% Aura Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Dexterity",
    valueRanges: [],
    rawAffix: "` +(15-20)` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Intelligence",
    valueRanges: [],
    rawAffix: "` +(15-20)` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Strength",
    valueRanges: [],
    rawAffix: "` +(15-20)` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-60) Max Mana",
    valueRanges: [],
    rawAffix: "` +(40-60)` Max Mana",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(54-74) Max Life",
    valueRanges: [],
    rawAffix: "` +(54-74)` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(87-117) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(87-117)` Max Energy Shield",
  },
] as const satisfies readonly BaseGearAffix[];

export type BeltSweetDreamAffixAffix =
  (typeof BELT_SWEET_DREAM_AFFIX_AFFIXES)[number];
