import { BaseGearAffix } from "./types";

export const BELT_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template:
      " (-50--40)% additional Damage Over Time taken when a Restoration Skill is active",
    valueRanges: [],
    rawAffix:
      "` (-50--40)`% additional Damage Over Time taken when a Restoration Skill is active",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Charged Flames Aura",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Charged Flames Aura",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Cruelty Aura Effect",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Cruelty Aura Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Deep Pain Aura",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Deep Pain Aura",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Electric Conversion Aura",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Electric Conversion Aura",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Fearless Aura",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Fearless Aura",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Frigid Domain Aura Effect",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Frigid Domain Aura Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Precise Projectiles Aura effect",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Precise Projectiles Aura effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Radical Order Aura Effect",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Radical Order Aura Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Spell Amplification Aura",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Spell Amplification Aura",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Weapon Amplification Aura",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Weapon Amplification Aura",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(3-5)% Max Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(3-5)`% Max Elemental Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(3-5)% Max Life",
    valueRanges: [],
    rawAffix: "` +(3-5)`% Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(4-6)% Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(4-6)`% Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(5-10)% Skill Area",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Skill Area",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Immune to crowd control effects",
    valueRanges: [],
    rawAffix: "Immune to crowd control effects",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Owns  1 additional stack(s) of Fortitude",
    valueRanges: [],
    rawAffix: "Owns ` 1` additional stack(s) of Fortitude",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Restoration Skills:  (-20--15)% Restoration Duration",
    valueRanges: [],
    rawAffix: "Restoration Skills: ` (-20--15)`% Restoration Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Restoration Skills:  +(30-40)% restoration effect",
    valueRanges: [],
    rawAffix: "Restoration Skills: ` +(30-40)`% restoration effect",
  },
] as const satisfies readonly BaseGearAffix[];

export type BeltCorrosionBaseAffix =
  (typeof BELT_CORROSION_BASE_AFFIXES)[number];
