import { BaseGearAffix } from "./types";

export const BELT_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(22-31)% Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(22-31)`% Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(25-31)% Skill Effect Duration",
    valueRanges: [],
    rawAffix: "` +(25-31)`% Skill Effect Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(27-34)% Wilt Duration",
    valueRanges: [],
    rawAffix: "` +(27-34)`% Wilt Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(27-34)% chance to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(27-34)`% chance to deal Double Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(33-42)% additional Deterioration Duration",
    valueRanges: [],
    rawAffix: "` +(33-42)`% additional Deterioration Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(37-54)% Freeze Duration",
    valueRanges: [],
    rawAffix: "` +(37-54)`% Freeze Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(40-50)% chance to launch one more wave when casting a Barrage Skill",
    valueRanges: [],
    rawAffix:
      "` +(40-50)`% chance to launch one more wave when casting a Barrage Skill",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(17-24)% Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(17-24)`% Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(18-24)% Skill Effect Duration",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Skill Effect Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(19-26)% Wilt Duration",
    valueRanges: [],
    rawAffix: "` +(19-26)`% Wilt Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(19-26)% chance to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(19-26)`% chance to deal Double Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(23-32)% additional Deterioration Duration",
    valueRanges: [],
    rawAffix: "` +(23-32)`% additional Deterioration Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(28-36)% Freeze Duration",
    valueRanges: [],
    rawAffix: "` +(28-36)`% Freeze Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(30-37)% chance to launch one more wave when casting a Barrage Skill",
    valueRanges: [],
    rawAffix:
      "` +(30-37)`% chance to launch one more wave when casting a Barrage Skill",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(10-12)% Elemental Resistance\n+(12-15)% chance to avoid Elemental Ailment",
    valueRanges: [],
    rawAffix:
      "` +(10-12)`% Elemental Resistance<> ` +(12-15)`% chance to avoid Elemental Ailment",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(13-16)% Ailment Duration",
    valueRanges: [],
    rawAffix: "` +(13-16)`% Ailment Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(33-42)% Max Mana",
    valueRanges: [],
    rawAffix: "` +(33-42)`% Max Mana",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(37-47)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(37-47)`% Focus Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(49-62) initial Growth for Spirit Magi",
    valueRanges: [],
    rawAffix: "` +(49-62)` initial Growth for Spirit Magi",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(51-65)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Affliction Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Warcry is cast immediately\n+2 Max Warcry Skill Charges",
    valueRanges: [],
    rawAffix: "Warcry is cast immediately<> ` +2` Max Warcry Skill Charges",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(23-32)% Max Mana",
    valueRanges: [],
    rawAffix: "` +(23-32)`% Max Mana",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(26-36)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(26-36)`% Focus Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(35-48) initial Growth for Spirit Magi",
    valueRanges: [],
    rawAffix: "` +(35-48)` initial Growth for Spirit Magi",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(36-50)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Affliction Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(7-9)% Elemental Resistance\n+(12-15)% chance to avoid Elemental Ailment",
    valueRanges: [],
    rawAffix:
      "` +(7-9)`% Elemental Resistance<> ` +(12-15)`% chance to avoid Elemental Ailment",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(8-12)% Ailment Duration",
    valueRanges: [],
    rawAffix: "` +(8-12)`% Ailment Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Warcry is cast immediately\n+1 Max Warcry Skill Charges",
    valueRanges: [],
    rawAffix: "Warcry is cast immediately<> ` +1` Max Warcry Skill Charges",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template:
      "Reaps  0.16 s of Damage Over Time when dealing Trauma Damage. The effect has a  1 s cooldown against the same target",
    valueRanges: [],
    rawAffix:
      "Reaps ` 0.16` s of Damage Over Time when dealing Trauma Damage. The effect has a ` 1` s cooldown against the same target",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template:
      "Reaps  0.16 s of Damage Over Time when inflicting Wilt . The effect has a  1 s cooldown against the same target",
    valueRanges: [],
    rawAffix:
      "Reaps ` 0.16` s of Damage Over Time when inflicting Wilt . The effect has a ` 1` s cooldown against the same target",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template:
      "Reaps  0.16 s of Damage Over Time when inflicting Ignite . The effect has a  1 s cooldown against the same target",
    valueRanges: [],
    rawAffix:
      "Reaps ` 0.16` s of Damage Over Time when inflicting Ignite . The effect has a ` 1` s cooldown against the same target",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template:
      "Reaps  0.12 s of Damage Over Time when dealing Trauma Damage. The effect has a  1 s cooldown against the same target",
    valueRanges: [],
    rawAffix:
      "Reaps ` 0.12` s of Damage Over Time when dealing Trauma Damage. The effect has a ` 1` s cooldown against the same target",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template:
      "Reaps  0.12 s of Damage Over Time when inflicting Wilt . The effect has a  1 s cooldown against the same target",
    valueRanges: [],
    rawAffix:
      "Reaps ` 0.12` s of Damage Over Time when inflicting Wilt . The effect has a ` 1` s cooldown against the same target",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template:
      "Reaps  0.12 s of Damage Over Time when inflicting Ignite . The effect has a  1 s cooldown against the same target",
    valueRanges: [],
    rawAffix:
      "Reaps ` 0.12` s of Damage Over Time when inflicting Ignite . The effect has a ` 1` s cooldown against the same target",
  },
] as const satisfies readonly BaseGearAffix[];

export type BeltSuffixAffix = (typeof BELT_SUFFIX_AFFIXES)[number];
