import { BaseGearAffix } from "./types";

export const BELT_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +10 Max Life",
    valueRanges: [],
    rawAffix: "` +10` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +110 Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +110` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +110 Max Life",
    valueRanges: [],
    rawAffix: "` +110` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +12 Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +12` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +140 Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +140` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +15 Max Life",
    valueRanges: [],
    rawAffix: "` +15` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +18 Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +18` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +35 Max Life",
    valueRanges: [],
    rawAffix: "` +35` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +50 Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +50` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +65 Max Life",
    valueRanges: [],
    rawAffix: "` +65` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +80 Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +80` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Belt",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +95 Max Life",
    valueRanges: [],
    rawAffix: "` +95` Max Life",
  },
] as const satisfies readonly BaseGearAffix[];

export type BeltBaseStatsAffix = (typeof BELT_BASE_STATS_AFFIXES)[number];
