import { BaseGearAffix } from "./types";

export const BOOTS_DEX_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " -45% additional Damage Over Time taken when having at least  50000 Evasion",
    valueRanges: [],
    rawAffix:
      "` -45`% additional Damage Over Time taken when having at least ` 50000` Evasion",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " (21-26)% of damage is taken from Mana before life",
    valueRanges: [],
    rawAffix: "` (21-26)`% of damage is taken from Mana before life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(16-20)% additional Max Life",
    valueRanges: [],
    rawAffix: "` +(16-20)`% additional Max Life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(31-40)% Spell Burst Charge Speed\n+10% chance to immediately gain  1 stack(s) of Spell Burst Charge when using a skill. Interval: 0.03s",
    valueRanges: [],
    rawAffix:
      "` +(31-40)`% Spell Burst Charge Speed<> ` +10`% chance to immediately gain ` 1` stack(s) of Spell Burst Charge when using a skill. Interval: 0.03s",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(31-40)% chance to avoid Spell Damage",
    valueRanges: [],
    rawAffix: "` +(31-40)`% chance to avoid Spell Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " 70% chance to gain Blur per  (5-10) m you move",
    valueRanges: [],
    rawAffix: "` 70`% chance to gain Blur per ` (5-10)` m you move",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Converts  (16-20)% of Physical Damage taken to Lightning Damage",
    valueRanges: [],
    rawAffix:
      "Converts ` (16-20)`% of Physical Damage taken to Lightning Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Converts  (36-45)% of Erosion Damage taken to Lightning Damage",
    valueRanges: [],
    rawAffix:
      "Converts ` (36-45)`% of Erosion Damage taken to Lightning Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Triggers Lv.  (11-20) Aim while standing still. Interval:  1 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` (11-20)` Aim while standing still. Interval: ` 1` s",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " -40% additional Damage Over Time taken when having at least  50000 Evasion",
    valueRanges: [],
    rawAffix:
      "` -40`% additional Damage Over Time taken when having at least ` 50000` Evasion",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " (15-20)% of damage is taken from Mana before life",
    valueRanges: [],
    rawAffix: "` (15-20)`% of damage is taken from Mana before life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(12-15)% additional Max Life",
    valueRanges: [],
    rawAffix: "` +(12-15)`% additional Max Life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(21-30)% Spell Burst Charge Speed\n+10% chance to immediately gain  1 stack(s) of Spell Burst Charge when using a skill. Interval: 0.03s",
    valueRanges: [],
    rawAffix:
      "` +(21-30)`% Spell Burst Charge Speed<> ` +10`% chance to immediately gain ` 1` stack(s) of Spell Burst Charge when using a skill. Interval: 0.03s",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(26-30)% chance to avoid Spell Damage",
    valueRanges: [],
    rawAffix: "` +(26-30)`% chance to avoid Spell Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " 50% chance to gain Blur per  (5-10) m you move",
    valueRanges: [],
    rawAffix: "` 50`% chance to gain Blur per ` (5-10)` m you move",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Converts  (12-15)% of Physical Damage taken to Lightning Damage",
    valueRanges: [],
    rawAffix:
      "Converts ` (12-15)`% of Physical Damage taken to Lightning Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Converts  (27-35)% of Erosion Damage taken to Lightning Damage",
    valueRanges: [],
    rawAffix:
      "Converts ` (27-35)`% of Erosion Damage taken to Lightning Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Triggers Lv.  (6-10) Aim while standing still. Interval:  1 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` (6-10)` Aim while standing still. Interval: ` 1` s",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(16-20)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(16-20)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(46-59)% Projectile Speed",
    valueRanges: [],
    rawAffix: "` +(46-59)`% Projectile Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +2 Cold Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Cold Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +2 Erosion Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Erosion Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +2 Fire Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Fire Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +2 Lightning Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Lightning Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +2 Minion Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Minion Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +2 Physical Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Physical Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(12-15)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(12-15)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(33-45)% Projectile Speed",
    valueRanges: [],
    rawAffix: "` +(33-45)`% Projectile Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +1 Cold Skill Level",
    valueRanges: [],
    rawAffix: "` +1` Cold Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +1 Erosion Skill Level",
    valueRanges: [],
    rawAffix: "` +1` Erosion Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +1 Fire Skill Level",
    valueRanges: [],
    rawAffix: "` +1` Fire Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +1 Lightning Skill Level",
    valueRanges: [],
    rawAffix: "` +1` Lightning Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +1 Minion Skill Level",
    valueRanges: [],
    rawAffix: "` +1` Minion Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +1 Physical Skill Level",
    valueRanges: [],
    rawAffix: "` +1` Physical Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156) Max Mana",
    valueRanges: [],
    rawAffix: "` +(121-156)` Max Mana",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(221-286) Max Life",
    valueRanges: [],
    rawAffix: "` +(221-286)` Max Life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(2881-3744) gear Evasion",
    valueRanges: [],
    rawAffix: "` +(2881-3744)` gear Evasion",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(61-78)% Critical Strike Damage Mitigation",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Critical Strike Damage Mitigation",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% Minion Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(154-220) Max Life",
    valueRanges: [],
    rawAffix: "` +(154-220)` Max Life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(2017-2880) gear Evasion",
    valueRanges: [],
    rawAffix: "` +(2017-2880)` gear Evasion",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(43-60)% Critical Strike Damage Mitigation",
    valueRanges: [],
    rawAffix: "` +(43-60)`% Critical Strike Damage Mitigation",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% Minion Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(85-120) Max Mana",
    valueRanges: [],
    rawAffix: "` +(85-120)` Max Mana",
  },
] as const satisfies readonly BaseGearAffix[];

export type BootsDexPrefixAffix = (typeof BOOTS_DEX_PREFIX_AFFIXES)[number];
