import { BaseGearAffix } from "./types";

export const BOOTS_STR_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(23-29)% additional Armor while moving",
    valueRanges: [],
    rawAffix: "` +(23-29)`% additional Armor while moving",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(27-34)% Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(27-34)`% Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(50-68)% chance to avoid Elemental Ailments",
    valueRanges: [],
    rawAffix: "` +(50-68)`% chance to avoid Elemental Ailments",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(84-108)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(84-108)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "For every  5 m moved, gains  1 stack(s) of Deflection",
    valueRanges: [],
    rawAffix: "For every ` 5` m moved, gains ` 1` stack(s) of Deflection",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      "Triggers Lv.  (11-20) Blurry Steps upon starting to move. Interval:  1 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` (11-20)` Blurry Steps upon starting to move. Interval: ` 1` s",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(17-22)% additional Armor while moving",
    valueRanges: [],
    rawAffix: "` +(17-22)`% additional Armor while moving",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(19-26)% Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(19-26)`% Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(30-45)% chance to avoid Elemental Ailments",
    valueRanges: [],
    rawAffix: "` +(30-45)`% chance to avoid Elemental Ailments",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(59-83)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(59-83)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "For every  6 m moved, gains  1 stack(s) of Deflection",
    valueRanges: [],
    rawAffix: "For every ` 6` m moved, gains ` 1` stack(s) of Deflection",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      "Triggers Lv.  (6-10) Blurry Steps upon starting to move. Interval:  1 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` (6-10)` Blurry Steps upon starting to move. Interval: ` 1` s",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(25-31)% Attack and Cast Speed\n+(25-31)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(25-31)`% Attack and Cast Speed<> ` +(25-31)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(25-31)% Attack and Cast Speed\n+(25-31)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(25-31)`% Attack and Cast Speed<> ` +(25-31)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(41-52)% Movement Speed",
    valueRanges: [],
    rawAffix: "` +(41-52)`% Movement Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(51-65)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Reaping Duration",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      "Has Hasten\n+(9-12)% Attack Speed, Cast Speed, and Movement Speed when having Hasten",
    valueRanges: [],
    rawAffix:
      "Has Hasten<> ` +(9-12)`% Attack Speed, Cast Speed, and Movement Speed when having Hasten",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(18-24)% Attack and Cast Speed\n+(18-24)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(18-24)`% Attack and Cast Speed<> ` +(18-24)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(29-40)% Movement Speed",
    valueRanges: [],
    rawAffix: "` +(29-40)`% Movement Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(36-50)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Reaping Duration",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(44-60)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(44-60)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      "Has Hasten\n+(5-8)% Attack Speed, Cast Speed, and Movement Speed when having Hasten",
    valueRanges: [],
    rawAffix:
      "Has Hasten<> ` +(5-8)`% Attack Speed, Cast Speed, and Movement Speed when having Hasten",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(121-156)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Cold Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Fire Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(51-65)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Affliction Effect",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "Regenerates  4% of Life per second while moving",
    valueRanges: [],
    rawAffix: "Regenerates ` 4`% of Life per second while moving",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Cold Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Fire Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(36-50)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Affliction Effect",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(87-120)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(87-120)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "Regenerates  3% of Life per second while moving",
    valueRanges: [],
    rawAffix: "Regenerates ` 3`% of Life per second while moving",
  },
] as const satisfies readonly BaseGearAffix[];

export type BootsStrSuffixAffix = (typeof BOOTS_STR_SUFFIX_AFFIXES)[number];
