import { BaseGearAffix } from "./types";

export const BOOTS_INT_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    craftableAffix: "(21-26)% of damage is taken from Mana before life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    craftableAffix: "+(16-20)% additional Max Energy Shield",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    craftableAffix:
      "+(31-40)% Spell Burst Charge Speed<> +10% chance to immediately gain 1stack(s) of Spell Burst Charge when using a skill. Interval: 0.03s",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    craftableAffix: "+(31-40)% chance to avoid Spell Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    craftableAffix: "70% chance to gain Blur per (5-10)m you move",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    craftableAffix: "Converts (16-20)% of Physical Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    craftableAffix: "Converts (36-45)% of Erosion Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    craftableAffix:
      "Triggers Lv. (11-20)Aim while standing still. Interval: 1s",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    craftableAffix: "(15-20)% of damage is taken from Mana before life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    craftableAffix: "+(12-15)% additional Max Energy Shield",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    craftableAffix:
      "+(21-30)% Spell Burst Charge Speed<> +10% chance to immediately gain 1stack(s) of Spell Burst Charge when using a skill. Interval: 0.03s",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    craftableAffix: "+(26-30)% chance to avoid Spell Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    craftableAffix: "50% chance to gain Blur per (5-10)m you move",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    craftableAffix: "Converts (12-15)% of Physical Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    craftableAffix: "Converts (27-35)% of Erosion Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    craftableAffix: "Triggers Lv. (6-10)Aim while standing still. Interval: 1s",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    craftableAffix: "+(16-20)% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    craftableAffix: "+(46-59)% Projectile Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    craftableAffix: "+2Cold Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    craftableAffix: "+2Erosion Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    craftableAffix: "+2Fire Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    craftableAffix: "+2Lightning Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    craftableAffix: "+2Minion Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    craftableAffix: "+2Physical Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    craftableAffix: "+(12-15)% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    craftableAffix: "+(33-45)% Projectile Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    craftableAffix: "+1Cold Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    craftableAffix: "+1Erosion Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    craftableAffix: "+1Fire Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    craftableAffix: "+1Lightning Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    craftableAffix: "+1Minion Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    craftableAffix: "+1Physical Skill Level",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    craftableAffix: "+(121-156)Max Mana",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    craftableAffix: "+(221-286)Max Life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    craftableAffix: "+(341-442)gear Energy Shield",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    craftableAffix: "+(61-78)% Critical Strike Damage Mitigation",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    craftableAffix: "+(61-86)% gear Energy Shield",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    craftableAffix: "+(73-94)% damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    craftableAffix: "+(73-94)% Minion Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    craftableAffix: "+(155-220)Max Life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    craftableAffix: "+(239-340)gear Energy Shield",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    craftableAffix: "+(43-60)% Critical Strike Damage Mitigation",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    craftableAffix: "+(47-66)% gear Energy Shield",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    craftableAffix: "+(51-72)% damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    craftableAffix: "+(51-72)% Minion Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    craftableAffix: "+(85-120)Max Mana",
  },
] as const satisfies readonly BaseGearAffix[];

export type BootsIntPrefixAffix = (typeof BOOTS_INT_PREFIX_AFFIXES)[number];
