import { BaseGearAffix } from "./types";

export const BOOTS_STR_SWEET_DREAM_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: " +(17-24)% Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(17-24)`% Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: " +(20-25)% Movement Speed",
    valueRanges: [],
    rawAffix: "` +(20-25)`% Movement Speed",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: " +(3-5)% Max Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(3-5)`% Max Elemental Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Converts  (12-15)% of Physical Damage taken to Fire Damage",
    valueRanges: [],
    rawAffix: "Converts ` (12-15)`% of Physical Damage taken to Fire Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Converts  (27-35)% of Erosion Damage taken to Fire Damage",
    valueRanges: [],
    rawAffix: "Converts ` (27-35)`% of Erosion Damage taken to Fire Damage",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +(5-7)% Armor DMG Mitigation Penetration\n+(5-7)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(5-7)`% Armor DMG Mitigation Penetration<> ` +(5-7)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +(6-8)% Elemental and Erosion Resistance Penetration\n+(6-8)% Elemental and Erosion Resistance Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(6-8)`% Elemental and Erosion Resistance Penetration<> ` +(6-8)`% Elemental and Erosion Resistance Penetration for Minions",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Dexterity",
    valueRanges: [],
    rawAffix: "` +(15-20)` Dexterity",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Intelligence",
    valueRanges: [],
    rawAffix: "` +(15-20)` Intelligence",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Strength",
    valueRanges: [],
    rawAffix: "` +(15-20)` Strength",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Skill Area",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Skill Area",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Cold Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Fire Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(54-74) Max Life",
    valueRanges: [],
    rawAffix: "` +(54-74)` Max Life",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(760-960) Armor",
    valueRanges: [],
    rawAffix: "` +(760-960)` Armor",
  },
] as const satisfies readonly BaseGearAffix[];

export type BootsStrSweetDreamAffixAffix =
  (typeof BOOTS_STR_SWEET_DREAM_AFFIX_AFFIXES)[number];
