import { BaseGearAffix } from "./types";

export const BOOTS_STR_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1122Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1346Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1615Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+168Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1777Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1920Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+235Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+329Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+461Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+599Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+779Gear Armor",
  },
  {
    equipmentSlot: "Boots",
    equipmentType: "Boots (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+935Gear Armor",
  },
] as const satisfies readonly BaseGearAffix[];

export type BootsStrBaseStatsAffix =
  (typeof BOOTS_STR_BASE_STATS_AFFIXES)[number];
