import { BaseGearAffix } from "./types";

export const BOW_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Multistrikes deal  (121-156)% increasing damage",
    valueRanges: [],
    rawAffix: "Multistrikes deal ` (121-156)`% increasing damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(111-145)% gear Physical Damage\nAdds  (69-71) -  (85-87) Physical Damage to the gear",
    valueRanges: [],
    rawAffix:
      "` +(111-145)`% gear Physical Damage<> Adds ` (69-71)` - ` (85-87)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(51-64)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(51-64)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(61-78)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +7 to Attack Skill Level",
    valueRanges: [],
    rawAffix: "` +7` to Attack Skill Level",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      "Adds  (77-79) -  (438-440) Elemental Damage to the gear\n-100% gear Physical Damage",
    valueRanges: [],
    rawAffix:
      "Adds ` (77-79)` - ` (438-440)` Elemental Damage to the gear<> ` -100`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Multistrikes deal  (85-120)% increasing damage",
    valueRanges: [],
    rawAffix: "Multistrikes deal ` (85-120)`% increasing damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(36-50)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(43-60)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(43-60)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(77-110)% gear Physical Damage\nAdds  (53-55) -  (65-67) Physical Damage to the gear",
    valueRanges: [],
    rawAffix:
      "` +(77-110)`% gear Physical Damage<> Adds ` (53-55)` - ` (65-67)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +6 to Attack Skill Level",
    valueRanges: [],
    rawAffix: "` +6` to Attack Skill Level",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      "Adds  (59-61) -  (337-339) Elemental Damage to the gear\n-100% gear Physical Damage",
    valueRanges: [],
    rawAffix:
      "Adds ` (59-61)` - ` (337-339)` Elemental Damage to the gear<> ` -100`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234) Dexterity",
    valueRanges: [],
    rawAffix: "` +(181-234)` Dexterity",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234) Intelligence",
    valueRanges: [],
    rawAffix: "` +(181-234)` Intelligence",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234) Strength",
    valueRanges: [],
    rawAffix: "` +(181-234)` Strength",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(46-59)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(46-59)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(81-104)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(81-104)`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180) Dexterity",
    valueRanges: [],
    rawAffix: "` +(127-180)` Dexterity",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180) Intelligence",
    valueRanges: [],
    rawAffix: "` +(127-180)` Intelligence",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180) Strength",
    valueRanges: [],
    rawAffix: "` +(127-180)` Strength",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(49-80)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(49-80)`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(197-281)% Projectile Damage",
    valueRanges: [],
    rawAffix: "` +(197-281)`% Projectile Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (198-200) -  (256-270) Fire Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (198-200)` - ` (256-270)` Fire Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (200-202) -  (266-268) Cold Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (200-202)` - ` (266-268)` Cold Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (214-216) -  (252-254) Erosion Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (214-216)` - ` (252-254)` Erosion Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (22-24) -  (444-446) Lightning Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (22-24)` - ` (444-446)` Lightning Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (93-95) -  (113-115) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (93-95)` - ` (113-115)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(152-216)% Projectile Damage",
    valueRanges: [],
    rawAffix: "` +(152-216)`% Projectile Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (152-154) -  (197-208) Fire Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (152-154)` - ` (197-208)` Fire Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (154-156) -  (204-206) Cold Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (154-156)` - ` (204-206)` Cold Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (165-167) -  (193-195) Erosion Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (165-167)` - ` (193-195)` Erosion Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (17-19) -  (341-343) Lightning Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (17-19)` - ` (341-343)` Lightning Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (71-73) -  (87-89) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (71-73)` - ` (87-89)` Physical Damage to the gear",
  },
] as const satisfies readonly BaseGearAffix[];

export type BowPrefixAffix = (typeof BOW_PREFIX_AFFIXES)[number];
