import { BaseGearAffix } from "./types";

export const BOW_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(1-2) Projectile Skill Level",
    valueRanges: [],
    rawAffix: "` +(1-2)` Projectile Skill Level",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-20)% Projectile Speed",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Projectile Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-25)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(15-25)`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(3-6)% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +(3-6)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(40-45)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(40-45)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(5-8)% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +(5-8)`% gear Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(6-12)% chance to gain 1 stack of Agility Blessing on defeat",
    valueRanges: [],
    rawAffix:
      "` +(6-12)`% chance to gain 1 stack of Agility Blessing on defeat",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Adds  (7-10) -  (14-17) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (7-10)` - ` (14-17)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Damage Penetrates  (8-12)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "Damage Penetrates ` (8-12)`% Elemental Resistance",
  },
] as const satisfies readonly BaseGearAffix[];

export type BowCorrosionBaseAffix = (typeof BOW_CORROSION_BASE_AFFIXES)[number];
