import { BaseGearAffix } from "./types";

export const BOW_BASE_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Lucky Critical Strike\n(-40--50)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "Lucky Critical Strike<> ` (-40--50)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Enemies have a  (20-25)% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to  (15-25)% of their Max Life to enemies within a  5 m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a ` (20-25)`% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to ` (15-25)`% of their Max Life to enemies within a ` 5` m radius",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Agility Blessing Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Agility Blessing Stacks ` +2` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Focus Blessing Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks ` +2` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Tenacity Blessing Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Tenacity Blessing Stacks ` +2` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(10-14)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(10-14)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(12-16)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(12-16)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(48-64)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(48-64)`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +2 Horizontal Projectile Penetration(s)",
    valueRanges: [],
    rawAffix: "` +2` Horizontal Projectile Penetration(s)",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "Adds  (64-68) -  (80-84) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (64-68)` - ` (80-84)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "Projectile Quantity  +2 ",
    valueRanges: [],
    rawAffix: "Projectile Quantity ` +2` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(12-16)% Attack Speed",
    valueRanges: [],
    rawAffix: "` +(12-16)`% Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Erosion Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Ranged Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Ranged Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (1-3) -  (60-65) Lightning Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (1-3)` - ` (60-65)` Lightning Damage to Attacks",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (24-29) -  (34-39) Cold Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (24-29)` - ` (34-39)` Cold Damage to Attacks",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (24-29) -  (34-39) Fire Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (24-29)` - ` (34-39)` Fire Damage to Attacks",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (25-30) -  (33-38) Physical Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (25-30)` - ` (33-38)` Physical Damage to Attacks",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Bow",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (26-31) -  (32-37) Erosion Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (26-31)` - ` (32-37)` Erosion Damage to Attacks",
  },
] as const satisfies readonly BaseGearAffix[];

export type BowBaseAffixAffix = (typeof BOW_BASE_AFFIX_AFFIXES)[number];
