import { BaseGearAffix } from "./types";

export const CHEST_ARMOR_DEX_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1091gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1309gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1571gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1885gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+196gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+2073gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+2240gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+274gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+384gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+538gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+699gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+909gear Evasion",
  },
] as const satisfies readonly BaseGearAffix[];

export type ChestArmorDexBaseStatsAffix =
  (typeof CHEST_ARMOR_DEX_BASE_STATS_AFFIXES)[number];
