import { BaseGearAffix } from "./types";

export const CHEST_ARMOR_INT_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(136-176) Attack and Spell Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(136-176)` Attack and Spell Critical Strike Rating",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(21-26)% Aura Effect",
    valueRanges: [],
    rawAffix: "` +(21-26)`% Aura Effect",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(50-68)% chance to avoid Elemental Ailments",
    valueRanges: [],
    rawAffix: "` +(50-68)`% chance to avoid Elemental Ailments",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(84-108)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(84-108)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(15-20)% Aura Effect",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Aura Effect",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(30-45)% chance to avoid Elemental Ailments",
    valueRanges: [],
    rawAffix: "` +(30-45)`% chance to avoid Elemental Ailments",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(59-83)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(59-83)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(96-135) Attack and Spell Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(96-135)` Attack and Spell Critical Strike Rating",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(11-13)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(11-13)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(19-23)% Intelligence",
    valueRanges: [],
    rawAffix: "` +(19-23)`% Intelligence",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(25-31)% Attack and Cast Speed\n+(25-31)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(25-31)`% Attack and Cast Speed<> ` +(25-31)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(51-65)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Reaping Duration",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      "Inflicts Cold Infiltration when dealing damage. Interval for each enemy:  1 s\nWhen Minions deal damage, inflicts Cold Infiltration . Interval for each enemy:  1 s\n+(40-60)% Cold Infiltration Effect",
    valueRanges: [],
    rawAffix:
      "Inflicts Cold Infiltration when dealing damage. Interval for each enemy: ` 1` s<> When Minions deal damage, inflicts Cold Infiltration . Interval for each enemy: ` 1` s<> ` +(40-60)`% Cold Infiltration Effect",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(14-18)% Intelligence",
    valueRanges: [],
    rawAffix: "` +(14-18)`% Intelligence",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(18-24)% Attack and Cast Speed\n+(18-24)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(18-24)`% Attack and Cast Speed<> ` +(18-24)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(36-50)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Reaping Duration",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(44-60)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(44-60)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(8-10)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(8-10)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      "Inflicts Cold Infiltration when dealing damage. Interval for each enemy:  1 s\nWhen Minions deal damage, inflicts Cold Infiltration . Interval for each enemy:  1 s\n+(10-30)% Cold Infiltration Effect",
    valueRanges: [],
    rawAffix:
      "Inflicts Cold Infiltration when dealing damage. Interval for each enemy: ` 1` s<> When Minions deal damage, inflicts Cold Infiltration . Interval for each enemy: ` 1` s<> ` +(10-30)`% Cold Infiltration Effect",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(121-156)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Cold Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Fire Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(51-65)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Affliction Effect",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(61-78)% Mana Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Mana Regeneration Speed",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Cold Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Fire Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(36-50)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Affliction Effect",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(43-60)% Mana Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(43-60)`% Mana Regeneration Speed",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(87-120)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(87-120)`% Critical Strike Rating",
  },
] as const satisfies readonly BaseGearAffix[];

export type ChestArmorIntSuffixAffix =
  (typeof CHEST_ARMOR_INT_SUFFIX_AFFIXES)[number];
