import { BaseGearAffix } from "./types";

export const CHEST_ARMOR_INT_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " (-6--4)% additional Physical Damage taken",
    valueRanges: [],
    rawAffix: "` (-6--4)`% additional Physical Damage taken",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(10-15)% Attack and Spell Block Chance while standing still",
    valueRanges: [],
    rawAffix: "` +(10-15)`% Attack and Spell Block Chance while standing still",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-20)% Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Max Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-20)% Max Life",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Max Life",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(3-5)% Max Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(3-5)`% Max Elemental Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(30-50)% gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +(30-50)`% gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(50-70)% damage",
    valueRanges: [],
    rawAffix: "` +(50-70)`% damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(8-10)% Elemental and Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(8-10)`% Elemental and Erosion Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +1 Support Skill Level",
    valueRanges: [],
    rawAffix: "` +1` Support Skill Level",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +2 Active Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Active Skill Level",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " 50% chance to gain Hardened when you are hit",
    valueRanges: [],
    rawAffix: "` 50`% chance to gain Hardened when you are hit",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Immune to Elemental Ailments",
    valueRanges: [],
    rawAffix: "Immune to Elemental Ailments",
  },
] as const satisfies readonly BaseGearAffix[];

export type ChestArmorIntCorrosionBaseAffix =
  (typeof CHEST_ARMOR_INT_CORROSION_BASE_AFFIXES)[number];
