import { BaseGearAffix } from "./types";

export const CHEST_ARMOR_INT_SWEET_DREAM_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: " +(3-5)% Max Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(3-5)`% Max Elemental Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: " +3 Max Fortitude Stacks",
    valueRanges: [],
    rawAffix: "` +3` Max Fortitude Stacks",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Converts  (12-15)% of Physical Damage taken to Cold Damage",
    valueRanges: [],
    rawAffix: "Converts ` (12-15)`% of Physical Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Converts  (27-35)% of Erosion Damage taken to Cold Damage",
    valueRanges: [],
    rawAffix: "Converts ` (27-35)`% of Erosion Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Takes 10 True Damage every 0.1s",
    valueRanges: [],
    rawAffix: "Takes 10 True Damage every 0.1s",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +(5-7)% Armor DMG Mitigation Penetration\n+(5-7)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(5-7)`% Armor DMG Mitigation Penetration<> ` +(5-7)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +(6-8)% Elemental and Erosion Resistance Penetration\n+(6-8)% Elemental and Erosion Resistance Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(6-8)`% Elemental and Erosion Resistance Penetration<> ` +(6-8)`% Elemental and Erosion Resistance Penetration for Minions",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(7-8)% Aura Effect",
    valueRanges: [],
    rawAffix: "` +(7-8)`% Aura Effect",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +1 Max Fortitude Stacks",
    valueRanges: [],
    rawAffix: "` +1` Max Fortitude Stacks",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Dexterity",
    valueRanges: [],
    rawAffix: "` +(15-20)` Dexterity",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Intelligence",
    valueRanges: [],
    rawAffix: "` +(15-20)` Intelligence",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Strength",
    valueRanges: [],
    rawAffix: "` +(15-20)` Strength",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Skill Area",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Skill Area",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(4-6)% Energy Shield Charge Speed",
    valueRanges: [],
    rawAffix: "` +(4-6)`% Energy Shield Charge Speed",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Cold Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Fire Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(87-117) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(87-117)` Max Energy Shield",
  },
] as const satisfies readonly BaseGearAffix[];

export type ChestArmorIntSweetDreamAffixAffix =
  (typeof CHEST_ARMOR_INT_SWEET_DREAM_AFFIX_AFFIXES)[number];
