import { BaseGearAffix } from "./types";

export const CHEST_ARMOR_INT_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+10gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+100gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+120gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+140gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+15gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+170gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+20gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+30gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+40gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+50gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+65gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+80gear Energy Shield",
  },
] as const satisfies readonly BaseGearAffix[];

export type ChestArmorIntBaseStatsAffix =
  (typeof CHEST_ARMOR_INT_BASE_STATS_AFFIXES)[number];
