import { BaseGearAffix } from "./types";

export const CHEST_ARMOR_INT_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " (21-26)% of damage is taken from Mana before life",
    valueRanges: [],
    rawAffix: "` (21-26)`% of damage is taken from Mana before life",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(16-20)% additional Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(16-20)`% additional Max Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(21-26)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(21-26)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Converts  (16-20)% of Physical Damage taken to Cold Damage",
    valueRanges: [],
    rawAffix: "Converts ` (16-20)`% of Physical Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Converts  (36-45)% of Erosion Damage taken to Cold Damage",
    valueRanges: [],
    rawAffix: "Converts ` (36-45)`% of Erosion Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      "Enemies have a  (20-25)% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to  (15-25)% of their Max Life to enemies within a  5 m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a ` (20-25)`% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to ` (15-25)`% of their Max Life to enemies within a ` 5` m radius",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "You can cast  1 additional Curses\n+(8-10)% curse effect",
    valueRanges: [],
    rawAffix: "You can cast ` 1` additional Curses<> ` +(8-10)`% curse effect",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " (15-20)% of damage is taken from Mana before life",
    valueRanges: [],
    rawAffix: "` (15-20)`% of damage is taken from Mana before life",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(12-15)% additional Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(12-15)`% additional Max Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(15-20)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Converts  (12-15)% of Physical Damage taken to Cold Damage",
    valueRanges: [],
    rawAffix: "Converts ` (12-15)`% of Physical Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Converts  (27-35)% of Erosion Damage taken to Cold Damage",
    valueRanges: [],
    rawAffix: "Converts ` (27-35)`% of Erosion Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      "Enemies have a  (10-15)% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to  (15-25)% of their Max Life to enemies within a  4 m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a ` (10-15)`% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to ` (15-25)`% of their Max Life to enemies within a ` 4` m radius",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "You can cast  1 additional Curses",
    valueRanges: [],
    rawAffix: "You can cast ` 1` additional Curses",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(16-20)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(16-20)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(46-59)% Projectile Speed",
    valueRanges: [],
    rawAffix: "` +(46-59)`% Projectile Speed",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Dexterity",
    valueRanges: [],
    rawAffix: "` +(61-78)` Dexterity",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Intelligence",
    valueRanges: [],
    rawAffix: "` +(61-78)` Intelligence",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Strength",
    valueRanges: [],
    rawAffix: "` +(61-78)` Strength",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(12-15)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(12-15)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(33-45)% Projectile Speed",
    valueRanges: [],
    rawAffix: "` +(33-45)`% Projectile Speed",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Dexterity",
    valueRanges: [],
    rawAffix: "` +(43-60)` Dexterity",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Intelligence",
    valueRanges: [],
    rawAffix: "` +(43-60)` Intelligence",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Strength",
    valueRanges: [],
    rawAffix: "` +(43-60)` Strength",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156) Max Mana",
    valueRanges: [],
    rawAffix: "` +(121-156)` Max Mana",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(221-286) Max Life",
    valueRanges: [],
    rawAffix: "` +(221-286)` Max Life",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(401-520) gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +(401-520)` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(61-78)% Critical Strike Damage Mitigation",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Critical Strike Damage Mitigation",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(61-86)% gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +(61-86)`% gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% Minion Damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(155-220) Max Life",
    valueRanges: [],
    rawAffix: "` +(155-220)` Max Life",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(281-400) gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +(281-400)` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(43-60)% Critical Strike Damage Mitigation",
    valueRanges: [],
    rawAffix: "` +(43-60)`% Critical Strike Damage Mitigation",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(47-66)% gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +(47-66)`% gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% Minion Damage",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(85-120) Max Mana",
    valueRanges: [],
    rawAffix: "` +(85-120)` Max Mana",
  },
] as const satisfies readonly BaseGearAffix[];

export type ChestArmorIntPrefixAffix =
  (typeof CHEST_ARMOR_INT_PREFIX_AFFIXES)[number];
