import { BaseGearAffix } from "./types";

export const CHEST_ARMOR_INT_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "",
    valueRanges: [],
    rawAffix: "",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "",
    valueRanges: [],
    rawAffix: "",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +10 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +10` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +100 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +100` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +120 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +120` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +140 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +140` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +15 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +15` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +170 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +170` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +20 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +20` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +30 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +30` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +40 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +40` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +50 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +50` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +65 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +65` gear Energy Shield",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +80 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +80` gear Energy Shield",
  },
] as const satisfies readonly BaseGearAffix[];

export type ChestArmorIntBaseStatsAffix =
  (typeof CHEST_ARMOR_INT_BASE_STATS_AFFIXES)[number];
