import { BaseGearAffix } from "./types";

export const CHEST_ARMOR_STR_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "",
    valueRanges: [],
    rawAffix: "",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1091 Gear Armor",
    valueRanges: [],
    rawAffix: "` +1091` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1309 Gear Armor",
    valueRanges: [],
    rawAffix: "` +1309` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1571 Gear Armor",
    valueRanges: [],
    rawAffix: "` +1571` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1885 Gear Armor",
    valueRanges: [],
    rawAffix: "` +1885` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +196 Gear Armor",
    valueRanges: [],
    rawAffix: "` +196` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +2073 Gear Armor",
    valueRanges: [],
    rawAffix: "` +2073` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +2240 Gear Armor",
    valueRanges: [],
    rawAffix: "` +2240` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +274 Gear Armor",
    valueRanges: [],
    rawAffix: "` +274` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +384 Gear Armor",
    valueRanges: [],
    rawAffix: "` +384` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +538 Gear Armor",
    valueRanges: [],
    rawAffix: "` +538` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +699 Gear Armor",
    valueRanges: [],
    rawAffix: "` +699` Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +909 Gear Armor",
    valueRanges: [],
    rawAffix: "` +909` Gear Armor",
  },
] as const satisfies readonly BaseGearAffix[];

export type ChestArmorStrBaseStatsAffix =
  (typeof CHEST_ARMOR_STR_BASE_STATS_AFFIXES)[number];
