import { BaseGearAffix } from "./types";

export const CHEST_ARMOR_STR_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1091Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1309Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1571Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1885Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+196Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+2073Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+2240Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+274Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+384Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+538Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+699Gear Armor",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+909Gear Armor",
  },
] as const satisfies readonly BaseGearAffix[];

export type ChestArmorStrBaseStatsAffix =
  (typeof CHEST_ARMOR_STR_BASE_STATS_AFFIXES)[number];
