import { BaseGearAffix } from "./types";

export const CHEST_ARMOR_DEX_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1091 gear Evasion",
    valueRanges: [],
    rawAffix: "` +1091` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1309 gear Evasion",
    valueRanges: [],
    rawAffix: "` +1309` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1571 gear Evasion",
    valueRanges: [],
    rawAffix: "` +1571` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1885 gear Evasion",
    valueRanges: [],
    rawAffix: "` +1885` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +196 gear Evasion",
    valueRanges: [],
    rawAffix: "` +196` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +2073 gear Evasion",
    valueRanges: [],
    rawAffix: "` +2073` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +2240 gear Evasion",
    valueRanges: [],
    rawAffix: "` +2240` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +274 gear Evasion",
    valueRanges: [],
    rawAffix: "` +274` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +384 gear Evasion",
    valueRanges: [],
    rawAffix: "` +384` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +538 gear Evasion",
    valueRanges: [],
    rawAffix: "` +538` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +699 gear Evasion",
    valueRanges: [],
    rawAffix: "` +699` gear Evasion",
  },
  {
    equipmentSlot: "Chest Armor",
    equipmentType: "Chest Armor (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +909 gear Evasion",
    valueRanges: [],
    rawAffix: "` +909` gear Evasion",
  },
] as const satisfies readonly BaseGearAffix[];

export type ChestArmorDexBaseStatsAffix =
  (typeof CHEST_ARMOR_DEX_BASE_STATS_AFFIXES)[number];
