import { BaseGearAffix } from "./types";

export const CROSSBOW_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-25)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(15-25)`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(3-6)% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +(3-6)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(40-45)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(40-45)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(5-8)% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +(5-8)`% gear Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(6-12)% chance to gain 1 stack of Tenacity Blessing on defeat",
    valueRanges: [],
    rawAffix:
      "` +(6-12)`% chance to gain 1 stack of Tenacity Blessing on defeat",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(8-12)% chance to deal double Trauma Damage",
    valueRanges: [],
    rawAffix: "` +(8-12)`% chance to deal double Trauma Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Adds  (7-10) -  (14-17) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (7-10)` - ` (14-17)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Eliminates enemies under  (5-8)% Life upon inflicting damage",
    valueRanges: [],
    rawAffix: "Eliminates enemies under ` (5-8)`% Life upon inflicting damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Crossbow",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template:
      "Enemies have a  30% chance to explode when defeated, dealing Secondary Physical Damage equal to  (5-10)% of their Max Life to enemies within a 5m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a ` 30`% chance to explode when defeated, dealing Secondary Physical Damage equal to ` (5-10)`% of their Max Life to enemies within a 5m radius",
  },
] as const satisfies readonly BaseGearAffix[];

export type CrossbowCorrosionBaseAffix =
  (typeof CROSSBOW_CORROSION_BASE_AFFIXES)[number];
