import { BaseGearAffix } from "./types";

export const DAGGER_PREFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Multistrikes deal  (61-78)% increasing damage",
    valueRanges: [],
    rawAffix: "Multistrikes deal ` (61-78)`% increasing damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(26-32)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(26-32)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(28-39)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(28-39)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(3-4) to Attack Skill Level",
    valueRanges: [],
    rawAffix: "` +(3-4)` to Attack Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(31-39)% additional Wilt Damage",
    valueRanges: [],
    rawAffix: "` +(31-39)`% additional Wilt Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      "Adds  (62-64) -  (356-358) Elemental Damage to the gear\n-100% gear Physical Damage",
    valueRanges: [],
    rawAffix:
      "Adds ` (62-64)` - ` (356-358)` Elemental Damage to the gear<> ` -100`% gear Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Multistrikes deal  (43-60)% increasing damage",
    valueRanges: [],
    rawAffix: "Multistrikes deal ` (43-60)`% increasing damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(18-25)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(18-25)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(22-30)% additional Wilt Damage",
    valueRanges: [],
    rawAffix: "` +(22-30)`% additional Wilt Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(22-30)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(22-30)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +3 to Attack Skill Level",
    valueRanges: [],
    rawAffix: "` +3` to Attack Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      "Adds  (47-49) -  (272-274) Elemental Damage to the gear\n-100% gear Physical Damage",
    valueRanges: [],
    rawAffix:
      "Adds ` (47-49)` - ` (272-274)` Elemental Damage to the gear<> ` -100`% gear Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(101-130)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(101-130)`% gear Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(23-29)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(23-29)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Dexterity",
    valueRanges: [],
    rawAffix: "` +(91-117)` Dexterity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Intelligence",
    valueRanges: [],
    rawAffix: "` +(91-117)` Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Strength",
    valueRanges: [],
    rawAffix: "` +(91-117)` Strength",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(56-100)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(56-100)`% gear Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Dexterity",
    valueRanges: [],
    rawAffix: "` +(64-90)` Dexterity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Intelligence",
    valueRanges: [],
    rawAffix: "` +(64-90)` Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Strength",
    valueRanges: [],
    rawAffix: "` +(64-90)` Strength",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Melee Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Melee Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (161-163) -  (208-220) Fire Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (161-163)` - ` (208-220)` Fire Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (162-164) -  (216-218) Cold Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (162-164)` - ` (216-218)` Cold Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (174-176) -  (204-206) Erosion Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (174-176)` - ` (204-206)` Erosion Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (18-20) -  (360-362) Lightning Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (18-20)` - ` (360-362)` Lightning Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (47-49) -  (57-59) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (47-49)` - ` (57-59)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template:
      "Reaps  (0.19-0.24) s of Wilt Damage when dealing Damage Over Time. The effect has a  1 s cooldown against the same target",
    valueRanges: [],
    rawAffix:
      "Reaps ` (0.19-0.24)` s of Wilt Damage when dealing Damage Over Time. The effect has a ` 1` s cooldown against the same target",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Melee Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Melee Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (123-125) -  (160-169) Fire Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (123-125)` - ` (160-169)` Fire Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (125-127) -  (165-167) Cold Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (125-127)` - ` (165-167)` Cold Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (133-135) -  (157-159) Erosion Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (133-135)` - ` (157-159)` Erosion Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (14-16) -  (276-278) Lightning Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (14-16)` - ` (276-278)` Lightning Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (36-38) -  (44-46) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (36-38)` - ` (44-46)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Dagger",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template:
      "Reaps  (0.13-0.18) s of Wilt Damage when dealing Damage Over Time. The effect has a  1 s cooldown against the same target",
    valueRanges: [],
    rawAffix:
      "Reaps ` (0.13-0.18)` s of Wilt Damage when dealing Damage Over Time. The effect has a ` 1` s cooldown against the same target",
  },
] as const satisfies readonly BaseGearAffix[];

export type DaggerPrefixAffix = (typeof DAGGER_PREFIX_AFFIXES)[number];
