import { BaseGearAffix } from "./types";

export const FIRE_CANNON_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Fire Cannon",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " -30% additional Damage Over Time taken while standing still",
    valueRanges: [],
    rawAffix: "` -30`% additional Damage Over Time taken while standing still",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Fire Cannon",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(10-15)% Skill Area",
    valueRanges: [],
    rawAffix: "` +(10-15)`% Skill Area",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Fire Cannon",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-25)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(15-25)`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Fire Cannon",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(3-6)% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +(3-6)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Fire Cannon",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(40-45)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(40-45)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Fire Cannon",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(5-8)% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +(5-8)`% gear Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Fire Cannon",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(6-12)% chance to gain 1 stack of Tenacity Blessing on defeat",
    valueRanges: [],
    rawAffix:
      "` +(6-12)`% chance to gain 1 stack of Tenacity Blessing on defeat",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Fire Cannon",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Adds  (7-10) -  (14-17) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (7-10)` - ` (14-17)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Fire Cannon",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Parabolic Projectile Splits quantity  +(1-2) ",
    valueRanges: [],
    rawAffix: "Parabolic Projectile Splits quantity ` +(1-2)` ",
  },
] as const satisfies readonly BaseGearAffix[];

export type FireCannonCorrosionBaseAffix =
  (typeof FIRE_CANNON_CORROSION_BASE_AFFIXES)[number];
