import { BaseGearAffix } from "./types";

export const GLOVES_DEX_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1122 gear Evasion",
    valueRanges: [],
    rawAffix: "` +1122` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1346 gear Evasion",
    valueRanges: [],
    rawAffix: "` +1346` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1615 gear Evasion",
    valueRanges: [],
    rawAffix: "` +1615` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +168 gear Evasion",
    valueRanges: [],
    rawAffix: "` +168` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1777 gear Evasion",
    valueRanges: [],
    rawAffix: "` +1777` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1920 gear Evasion",
    valueRanges: [],
    rawAffix: "` +1920` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +235 gear Evasion",
    valueRanges: [],
    rawAffix: "` +235` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +329 gear Evasion",
    valueRanges: [],
    rawAffix: "` +329` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +461 gear Evasion",
    valueRanges: [],
    rawAffix: "` +461` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +599 gear Evasion",
    valueRanges: [],
    rawAffix: "` +599` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +779 gear Evasion",
    valueRanges: [],
    rawAffix: "` +779` gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +935 gear Evasion",
    valueRanges: [],
    rawAffix: "` +935` gear Evasion",
  },
] as const satisfies readonly BaseGearAffix[];

export type GlovesDexBaseStatsAffix =
  (typeof GLOVES_DEX_BASE_STATS_AFFIXES)[number];
