import { BaseGearAffix } from "./types";

export const GLOVES_DEX_SWEET_DREAM_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: " +(3-5)% Max Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(3-5)`% Max Elemental Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +(5-7)% Armor DMG Mitigation Penetration\n+(5-7)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(5-7)`% Armor DMG Mitigation Penetration<> ` +(5-7)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +(6-8)% Elemental and Erosion Resistance Penetration\n+(6-8)% Elemental and Erosion Resistance Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(6-8)`% Elemental and Erosion Resistance Penetration<> ` +(6-8)`% Elemental and Erosion Resistance Penetration for Minions",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(7-8)% Aura Effect",
    valueRanges: [],
    rawAffix: "` +(7-8)`% Aura Effect",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +100% chance to Paralyze the target on hit",
    valueRanges: [],
    rawAffix: "` +100`% chance to Paralyze the target on hit",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Dexterity",
    valueRanges: [],
    rawAffix: "` +(15-20)` Dexterity",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Intelligence",
    valueRanges: [],
    rawAffix: "` +(15-20)` Intelligence",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Strength",
    valueRanges: [],
    rawAffix: "` +(15-20)` Strength",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Skill Area",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Skill Area",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Cold Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Fire Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(54-74) Max Life",
    valueRanges: [],
    rawAffix: "` +(54-74)` Max Life",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(760-960) Evasion",
    valueRanges: [],
    rawAffix: "` +(760-960)` Evasion",
  },
] as const satisfies readonly BaseGearAffix[];

export type GlovesDexSweetDreamAffixAffix =
  (typeof GLOVES_DEX_SWEET_DREAM_AFFIX_AFFIXES)[number];
