import { BaseGearAffix } from "./types";

export const GLOVES_STR_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Lucky Critical Strike\n(-150--120) Critical Strike Rating",
    valueRanges: [],
    rawAffix: "Lucky Critical Strike<> ` (-150--120)` Critical Strike Rating",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(12-15)% Attack Speed",
    valueRanges: [],
    rawAffix: "` +(12-15)`% Attack Speed",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(12-15)% Cast Speed",
    valueRanges: [],
    rawAffix: "` +(12-15)`% Cast Speed",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-20)% chance to Mark the target on hit",
    valueRanges: [],
    rawAffix: "` +(15-20)`% chance to Mark the target on hit",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-20)% chance to cause Blinding on hit",
    valueRanges: [],
    rawAffix: "` +(15-20)`% chance to cause Blinding on hit",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-20)% chance to inflict Paralysis on hit",
    valueRanges: [],
    rawAffix: "` +(15-20)`% chance to inflict Paralysis on hit",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(30-50)% Gear Armor",
    valueRanges: [],
    rawAffix: "` +(30-50)`% Gear Armor",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(50-70)% damage",
    valueRanges: [],
    rawAffix: "` +(50-70)`% damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Converts  50% of Physical Damage to Cold Damage",
    valueRanges: [],
    rawAffix: "Converts ` 50`% of Physical Damage to Cold Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Converts  50% of Physical Damage to Erosion Damage",
    valueRanges: [],
    rawAffix: "Converts ` 50`% of Physical Damage to Erosion Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Converts  50% of Physical Damage to Lightning Damage",
    valueRanges: [],
    rawAffix: "Converts ` 50`% of Physical Damage to Lightning Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Converts  50% Physical Damage to Fire Damage",
    valueRanges: [],
    rawAffix: "Converts ` 50`% Physical Damage to Fire Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Eliminates enemies under  15% Life upon inflicting damage",
    valueRanges: [],
    rawAffix: "Eliminates enemies under ` 15`% Life upon inflicting damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Gains a stack of Fortitude when using a Melee Skill",
    valueRanges: [],
    rawAffix: "Gains a stack of Fortitude when using a Melee Skill",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Gains a stack of Torment when Reaping",
    valueRanges: [],
    rawAffix: "Gains a stack of Torment when Reaping",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Inflicts Frail when dealing Spell Damage",
    valueRanges: [],
    rawAffix: "Inflicts Frail when dealing Spell Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Max Tenacity Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Tenacity Blessing Stacks ` +1` ",
  },
] as const satisfies readonly BaseGearAffix[];

export type GlovesStrCorrosionBaseAffix =
  (typeof GLOVES_STR_CORROSION_BASE_AFFIXES)[number];
