import { BaseGearAffix } from "./types";

export const GLOVES_DEX_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1122gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1346gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1615gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+168gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1777gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+1920gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+235gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+329gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+461gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+599gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+779gear Evasion",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (DEX)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+935gear Evasion",
  },
] as const satisfies readonly BaseGearAffix[];

export type GlovesDexBaseStatsAffix =
  (typeof GLOVES_DEX_BASE_STATS_AFFIXES)[number];
