import { BaseGearAffix } from "./types";

export const GLOVES_INT_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(16-20)% Blur Effect\nGains Blur for  1 s after losing Blur",
    valueRanges: [],
    rawAffix:
      "` +(16-20)`% Blur Effect<> Gains Blur for ` 1` s after losing Blur",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(26-30)% additional damage while having Fervor",
    valueRanges: [],
    rawAffix: "` +(26-30)`% additional damage while having Fervor",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(84-108)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(84-108)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +1 Jumps\n+6% additional damage for every Jump (multiplies)",
    valueRanges: [],
    rawAffix:
      "` +1` Jumps<> ` +6`% additional damage for every Jump (multiplies)",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(12-15)% Blur Effect\nGains Blur for  1 s after losing Blur",
    valueRanges: [],
    rawAffix:
      "` +(12-15)`% Blur Effect<> Gains Blur for ` 1` s after losing Blur",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(21-25)% additional damage while having Fervor",
    valueRanges: [],
    rawAffix: "` +(21-25)`% additional damage while having Fervor",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(59-83)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(59-83)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +1 Jumps\n+(4-5)% additional damage for every Jump (multiplies)",
    valueRanges: [],
    rawAffix:
      "` +1` Jumps<> ` +(4-5)`% additional damage for every Jump (multiplies)",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(22-31)% Attack and Cast Speed\n+(22-31)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(22-31)`% Attack and Cast Speed<> ` +(22-31)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(49-62)% Skill Area\n+(49-62)% Minion Skill Area",
    valueRanges: [],
    rawAffix: "` +(49-62)`% Skill Area<> ` +(49-62)`% Minion Skill Area",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(51-65)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Reaping Duration",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(17-24)% Attack and Cast Speed\n+(17-24)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(17-24)`% Attack and Cast Speed<> ` +(17-24)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(35-48)% Skill Area\n+(35-48)% Minion Skill Area",
    valueRanges: [],
    rawAffix: "` +(35-48)`% Skill Area<> ` +(35-48)`% Minion Skill Area",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(37-50)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(37-50)`% Reaping Duration",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(44-60)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(44-60)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(111-156)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(111-156)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Cold Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Fire Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(51-65)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Affliction Effect",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Cold Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Fire Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(36-50)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Affliction Effect",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(85-120)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(85-120)`% Critical Strike Rating",
  },
] as const satisfies readonly BaseGearAffix[];

export type GlovesIntSuffixAffix = (typeof GLOVES_INT_SUFFIX_AFFIXES)[number];
