import { BaseGearAffix } from "./types";

export const GLOVES_INT_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(26-30)% additional Minion Damage when you have  (1-8) Minion(s)",
    valueRanges: [],
    rawAffix:
      "` +(26-30)`% additional Minion Damage when you have ` (1-8)` Minion(s)",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(9-10)% additional Cold Damage and  +(16-18)% Cold Penetration when having at least  8 stack(s) of Focus Blessing",
    valueRanges: [],
    rawAffix:
      "` +(9-10)`% additional Cold Damage and ` +(16-18)`% Cold Penetration when having at least ` 8` stack(s) of Focus Blessing",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(9-10)% additional Fire Damage and  +(16-18)% Fire Penetration when having at least  8 stack(s) of Tenacity Blessing",
    valueRanges: [],
    rawAffix:
      "` +(9-10)`% additional Fire Damage and ` +(16-18)`% Fire Penetration when having at least ` 8` stack(s) of Tenacity Blessing",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(9-10)% additional Lightning Damage and  +(16-18)% Lightning Penetration when having at least  8 stack(s) of Agility Blessing",
    valueRanges: [],
    rawAffix:
      "` +(9-10)`% additional Lightning Damage and ` +(16-18)`% Lightning Penetration when having at least ` 8` stack(s) of Agility Blessing",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +3 Active Skill Level",
    valueRanges: [],
    rawAffix: "` +3` Active Skill Level",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(21-25)% additional Minion Damage when you have  (1-8) Minion(s)",
    valueRanges: [],
    rawAffix:
      "` +(21-25)`% additional Minion Damage when you have ` (1-8)` Minion(s)",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(6-8)% additional Cold Damage and  +(12-15)% Cold Penetration when having at least  8 stack(s) of Focus Blessing",
    valueRanges: [],
    rawAffix:
      "` +(6-8)`% additional Cold Damage and ` +(12-15)`% Cold Penetration when having at least ` 8` stack(s) of Focus Blessing",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(6-8)% additional Fire Damage and  +(12-15)% Fire Penetration when having at least  8 stack(s) of Tenacity Blessing",
    valueRanges: [],
    rawAffix:
      "` +(6-8)`% additional Fire Damage and ` +(12-15)`% Fire Penetration when having at least ` 8` stack(s) of Tenacity Blessing",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(6-8)% additional Lightning Damage and  +(12-15)% Lightning Penetration when having at least  8 stack(s) of Agility Blessing",
    valueRanges: [],
    rawAffix:
      "` +(6-8)`% additional Lightning Damage and ` +(12-15)`% Lightning Penetration when having at least ` 8` stack(s) of Agility Blessing",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +2 Active Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Active Skill Level",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (13-16)% of Cold Damage as Erosion Damage",
    valueRanges: [],
    rawAffix: "Adds ` (13-16)`% of Cold Damage as Erosion Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (13-16)% of Physical Damage to Cold Damage",
    valueRanges: [],
    rawAffix: "Adds ` (13-16)`% of Physical Damage to Cold Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (54-56) -  (71-76) Fire Damage to Attacks and Spells",
    valueRanges: [],
    rawAffix: "Adds ` (54-56)` - ` (71-76)` Fire Damage to Attacks and Spells",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (55-57) -  (73-75) Cold Damage to Attacks and Spells",
    valueRanges: [],
    rawAffix: "Adds ` (55-57)` - ` (73-75)` Cold Damage to Attacks and Spells",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (55-57) -  (73-75) Erosion Damage to Attacks and Spells",
    valueRanges: [],
    rawAffix:
      "Adds ` (55-57)` - ` (73-75)` Erosion Damage to Attacks and Spells",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (58-60) -  (71-73) Physical Damage to Attacks and Spells",
    valueRanges: [],
    rawAffix:
      "Adds ` (58-60)` - ` (71-73)` Physical Damage to Attacks and Spells",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (6-8) -  (123-125) Lightning Damage to Attacks and Spells",
    valueRanges: [],
    rawAffix:
      "Adds ` (6-8)` - ` (123-125)` Lightning Damage to Attacks and Spells",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (4-6) -  (94-96) Lightning Damage to Attacks and Spells",
    valueRanges: [],
    rawAffix:
      "Adds ` (4-6)` - ` (94-96)` Lightning Damage to Attacks and Spells",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (42-44) -  (54-59) Fire Damage to Attacks and Spells",
    valueRanges: [],
    rawAffix: "Adds ` (42-44)` - ` (54-59)` Fire Damage to Attacks and Spells",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (42-44) -  (56-58) Cold Damage to Attacks and Spells",
    valueRanges: [],
    rawAffix: "Adds ` (42-44)` - ` (56-58)` Cold Damage to Attacks and Spells",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (42-44) -  (56-58) Erosion Damage to Attacks and Spells",
    valueRanges: [],
    rawAffix:
      "Adds ` (42-44)` - ` (56-58)` Erosion Damage to Attacks and Spells",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (44-46) -  (54-56) Physical Damage to Attacks and Spells",
    valueRanges: [],
    rawAffix:
      "Adds ` (44-46)` - ` (54-56)` Physical Damage to Attacks and Spells",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (9-12)% of Cold Damage as Erosion Damage",
    valueRanges: [],
    rawAffix: "Adds ` (9-12)`% of Cold Damage as Erosion Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (9-12)% of Physical Damage to Cold Damage",
    valueRanges: [],
    rawAffix: "Adds ` (9-12)`% of Physical Damage to Cold Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156) Max Mana",
    valueRanges: [],
    rawAffix: "` +(121-156)` Max Mana",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(221-286) Max Life",
    valueRanges: [],
    rawAffix: "` +(221-286)` Max Life",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(26-37)% Frostbite inflicted",
    valueRanges: [],
    rawAffix: "` +(26-37)`% Frostbite inflicted",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(341-442) gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +(341-442)` gear Energy Shield",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(61-78)% Critical Strike Damage Mitigation",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Critical Strike Damage Mitigation",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(61-78)% Mana Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Mana Regeneration Speed",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(61-86)% gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +(61-86)`% gear Energy Shield",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% Minion Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(155-220) Max Life",
    valueRanges: [],
    rawAffix: "` +(155-220)` Max Life",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(20-25)% Frostbite inflicted",
    valueRanges: [],
    rawAffix: "` +(20-25)`% Frostbite inflicted",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(239-340) gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +(239-340)` gear Energy Shield",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(43-60)% Critical Strike Damage Mitigation",
    valueRanges: [],
    rawAffix: "` +(43-60)`% Critical Strike Damage Mitigation",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(43-60)% Mana Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(43-60)`% Mana Regeneration Speed",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(47-66)% gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +(47-66)`% gear Energy Shield",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% Minion Damage",
  },
  {
    equipmentSlot: "Gloves",
    equipmentType: "Gloves (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(85-120) Max Mana",
    valueRanges: [],
    rawAffix: "` +(85-120)` Max Mana",
  },
] as const satisfies readonly BaseGearAffix[];

export type GlovesIntPrefixAffix = (typeof GLOVES_INT_PREFIX_AFFIXES)[number];
