import { BaseGearAffix } from "./types";

export const HELMET_INT_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " (-50--30)% Cursed Effect",
    valueRanges: [],
    rawAffix: "` (-50--30)`% Cursed Effect",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(10-15)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(10-15)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-20)% Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Max Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-20)% Max Life",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Max Life",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(30-50)% gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +(30-50)`% gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(50-70)% damage",
    valueRanges: [],
    rawAffix: "` +(50-70)`% damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Immune to Blinding\nImmune to Paralysis",
    valueRanges: [],
    rawAffix: "Immune to Blinding<> Immune to Paralysis",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Max Focus Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  (15-20) Timid Curse upon inflicting damage. Cooldown:  0.3 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` (15-20)` Timid Curse upon inflicting damage. Cooldown: ` 0.3` s",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  (15-20) Entangled Pain Curse upon inflicting damage. Cooldown:  0.3 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` (15-20)` Entangled Pain Curse upon inflicting damage. Cooldown: ` 0.3` s",
  },
] as const satisfies readonly BaseGearAffix[];

export type HelmetIntCorrosionBaseAffix =
  (typeof HELMET_INT_CORROSION_BASE_AFFIXES)[number];
