import { BaseGearAffix } from "./types";

export const HELMET_STR_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " -45% additional Damage Over Time taken when having at least  50000 Armor",
    valueRanges: [],
    rawAffix:
      "` -45`% additional Damage Over Time taken when having at least ` 50000` Armor",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " (-20--16)% additional Damage dealt by Nearby enemies",
    valueRanges: [],
    rawAffix: "` (-20--16)`% additional Damage dealt by Nearby enemies",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " (21-26)% of damage is taken from Mana before life",
    valueRanges: [],
    rawAffix: "` (21-26)`% of damage is taken from Mana before life",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(21-26)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(21-26)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +1 Max Spell Burst\n+10% additional Hit Damage for skills cast by Spell Burst",
    valueRanges: [],
    rawAffix:
      "` +1` Max Spell Burst<> ` +10`% additional Hit Damage for skills cast by Spell Burst",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Converts  (16-20)% of Physical Damage taken to Fire Damage",
    valueRanges: [],
    rawAffix: "Converts ` (16-20)`% of Physical Damage taken to Fire Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Converts  (36-45)% of Erosion Damage taken to Fire Damage",
    valueRanges: [],
    rawAffix: "Converts ` (36-45)`% of Erosion Damage taken to Fire Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Terra Charge Stacks  +1 \n+30% Terra Charge Recovery Speed",
    valueRanges: [],
    rawAffix:
      "Max Terra Charge Stacks ` +1` <> ` +30`% Terra Charge Recovery Speed",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " -40% additional Damage Over Time taken when having at least  50000 Armor",
    valueRanges: [],
    rawAffix:
      "` -40`% additional Damage Over Time taken when having at least ` 50000` Armor",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " (-15--12)% additional Damage dealt by Nearby enemies",
    valueRanges: [],
    rawAffix: "` (-15--12)`% additional Damage dealt by Nearby enemies",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " (15-20)% of damage is taken from Mana before life",
    valueRanges: [],
    rawAffix: "` (15-20)`% of damage is taken from Mana before life",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(15-20)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +1 Max Spell Burst",
    valueRanges: [],
    rawAffix: "` +1` Max Spell Burst",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Converts  (12-15)% of Physical Damage taken to Fire Damage",
    valueRanges: [],
    rawAffix: "Converts ` (12-15)`% of Physical Damage taken to Fire Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Converts  (27-35)% of Erosion Damage taken to Fire Damage",
    valueRanges: [],
    rawAffix: "Converts ` (27-35)`% of Erosion Damage taken to Fire Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Terra Charge Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Terra Charge Stacks ` +1` ",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(14-17)% Block Ratio",
    valueRanges: [],
    rawAffix: "` +(14-17)`% Block Ratio",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(46-59)% Projectile Speed",
    valueRanges: [],
    rawAffix: "` +(46-59)`% Projectile Speed",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(51-65)% chance to gain 1 stack of Tenacity Blessing on defeat",
    valueRanges: [],
    rawAffix:
      "` +(51-65)`% chance to gain 1 stack of Tenacity Blessing on defeat",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Dexterity",
    valueRanges: [],
    rawAffix: "` +(61-78)` Dexterity",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Intelligence",
    valueRanges: [],
    rawAffix: "` +(61-78)` Intelligence",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Strength",
    valueRanges: [],
    rawAffix: "` +(61-78)` Strength",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78)% Barrier Shield",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Barrier Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(10-13)% Block Ratio",
    valueRanges: [],
    rawAffix: "` +(10-13)`% Block Ratio",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(33-45)% Projectile Speed",
    valueRanges: [],
    rawAffix: "` +(33-45)`% Projectile Speed",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(37-50)% chance to gain 1 stack of Tenacity Blessing on defeat",
    valueRanges: [],
    rawAffix:
      "` +(37-50)`% chance to gain 1 stack of Tenacity Blessing on defeat",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Dexterity",
    valueRanges: [],
    rawAffix: "` +(43-60)` Dexterity",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Intelligence",
    valueRanges: [],
    rawAffix: "` +(43-60)` Intelligence",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Strength",
    valueRanges: [],
    rawAffix: "` +(43-60)` Strength",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60)% Barrier Shield",
    valueRanges: [],
    rawAffix: "` +(43-60)`% Barrier Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156) Max Mana",
    valueRanges: [],
    rawAffix: "` +(121-156)` Max Mana",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(221-286) Max Life",
    valueRanges: [],
    rawAffix: "` +(221-286)` Max Life",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(2622-3744) Gear Armor",
    valueRanges: [],
    rawAffix: "` +(2622-3744)` Gear Armor",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% Minion Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(154-220) Max Life",
    valueRanges: [],
    rawAffix: "` +(154-220)` Max Life",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(2017-2880) Gear Armor",
    valueRanges: [],
    rawAffix: "` +(2017-2880)` Gear Armor",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% Minion Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(85-120) Max Mana",
    valueRanges: [],
    rawAffix: "` +(85-120)` Max Mana",
  },
] as const satisfies readonly BaseGearAffix[];

export type HelmetStrPrefixAffix = (typeof HELMET_STR_PREFIX_AFFIXES)[number];
