import { BaseGearAffix } from "./types";

export const HELMET_STR_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(10-11) Support Skill Level",
    valueRanges: [],
    rawAffix: "` +(10-11)` Support Skill Level",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(25-31)% additional damage taken by Nearby enemies",
    valueRanges: [],
    rawAffix: "` +(25-31)`% additional damage taken by Nearby enemies",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(41-52)% Numbed Effect",
    valueRanges: [],
    rawAffix: "` +(41-52)`% Numbed Effect",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(50-68)% chance to avoid Elemental Ailments",
    valueRanges: [],
    rawAffix: "` +(50-68)`% chance to avoid Elemental Ailments",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(84-108)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(84-108)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(18-24)% additional damage taken by Nearby enemies",
    valueRanges: [],
    rawAffix: "` +(18-24)`% additional damage taken by Nearby enemies",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(29-40)% Numbed Effect",
    valueRanges: [],
    rawAffix: "` +(29-40)`% Numbed Effect",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(30-45)% chance to avoid Elemental Ailments",
    valueRanges: [],
    rawAffix: "` +(30-45)`% chance to avoid Elemental Ailments",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(59-83)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(59-83)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(6-9) Support Skill Level",
    valueRanges: [],
    rawAffix: "` +(6-9)` Support Skill Level",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " (11-15)% chance to gain a Barrier on defeat",
    valueRanges: [],
    rawAffix: "` (11-15)`% chance to gain a Barrier on defeat",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(19-23)% Armor\n+(11-143) Max Life",
    valueRanges: [],
    rawAffix: "` +(19-23)`% Armor<> ` +(11-143)` Max Life",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(25-31)% Attack and Cast Speed\n+(25-31)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(25-31)`% Attack and Cast Speed<> ` +(25-31)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(37-47)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(37-47)`% Focus Speed",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(49-62)% Skill Area\n+(49-62)% Minion Skill Area",
    valueRanges: [],
    rawAffix: "` +(49-62)`% Skill Area<> ` +(49-62)`% Minion Skill Area",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(51-65)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Reaping Duration",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(14-18)% Armor\n+(78-110) Max Life",
    valueRanges: [],
    rawAffix: "` +(14-18)`% Armor<> ` +(78-110)` Max Life",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(18-24)% Attack and Cast Speed\n+(18-24)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(18-24)`% Attack and Cast Speed<> ` +(18-24)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(26-36)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(26-36)`% Focus Speed",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(35-48)% Skill Area\n+(35-48)% Minion Skill Area",
    valueRanges: [],
    rawAffix: "` +(35-48)`% Skill Area<> ` +(35-48)`% Minion Skill Area",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(36-50)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Reaping Duration",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(44-60)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(44-60)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(121-156)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Cold Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Fire Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(51-65)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Affliction Effect",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "Regenerates  (121-156) Life per second",
    valueRanges: [],
    rawAffix: "Regenerates ` (121-156)` Life per second",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Cold Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Fire Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(36-50)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Affliction Effect",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(87-120)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(87-120)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "Regenerates  (85-120) Life per second",
    valueRanges: [],
    rawAffix: "Regenerates ` (85-120)` Life per second",
  },
] as const satisfies readonly BaseGearAffix[];

export type HelmetStrSuffixAffix = (typeof HELMET_STR_SUFFIX_AFFIXES)[number];
