import { BaseGearAffix } from "./types";

export const HELMET_INT_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +103 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +103` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +120 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +120` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +13 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +13` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +146 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +146` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +18 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +18` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +26 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +26` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +35 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +35` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +43 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +43` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +56 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +56` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +69 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +69` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +86 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +86` gear Energy Shield",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +9 gear Energy Shield",
    valueRanges: [],
    rawAffix: "` +9` gear Energy Shield",
  },
] as const satisfies readonly BaseGearAffix[];

export type HelmetIntBaseStatsAffix =
  (typeof HELMET_INT_BASE_STATS_AFFIXES)[number];
