import { BaseGearAffix } from "./types";

export const HELMET_STR_BASE_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: " +(13-14)% Armor Effective Rate for Non-Physical Damage",
    valueRanges: [],
    rawAffix: "` +(13-14)`% Armor Effective Rate for Non-Physical Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: " +(3-5)% Max Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(3-5)`% Max Elemental Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Converts  (12-15)% of Physical Damage taken to Fire Damage",
    valueRanges: [],
    rawAffix: "Converts ` (12-15)`% of Physical Damage taken to Fire Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Converts  (27-35)% of Erosion Damage taken to Fire Damage",
    valueRanges: [],
    rawAffix: "Converts ` (27-35)`% of Erosion Damage taken to Fire Damage",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +(5-7)% Armor DMG Mitigation Penetration\n+(5-7)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(5-7)`% Armor DMG Mitigation Penetration<> ` +(5-7)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +(6-8)% Elemental and Erosion Resistance Penetration\n+(6-8)% Elemental and Erosion Resistance Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(6-8)`% Elemental and Erosion Resistance Penetration<> ` +(6-8)`% Elemental and Erosion Resistance Penetration for Minions",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(7-8)% Aura Effect",
    valueRanges: [],
    rawAffix: "` +(7-8)`% Aura Effect",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template:
      "When dealing damage, inflicts Fire Infiltration . Interval for each enemy:  1 s\nWhen Minions deal damage, inflicts Fire Infiltration . Interval for each enemy:  1 s",
    valueRanges: [],
    rawAffix:
      "When dealing damage, inflicts Fire Infiltration . Interval for each enemy: ` 1` s<> When Minions deal damage, inflicts Fire Infiltration . Interval for each enemy: ` 1` s",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Dexterity",
    valueRanges: [],
    rawAffix: "` +(15-20)` Dexterity",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Intelligence",
    valueRanges: [],
    rawAffix: "` +(15-20)` Intelligence",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Strength",
    valueRanges: [],
    rawAffix: "` +(15-20)` Strength",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Skill Area",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Skill Area",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Cold Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Fire Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(54-74) Max Life",
    valueRanges: [],
    rawAffix: "` +(54-74)` Max Life",
  },
  {
    equipmentSlot: "Helmet",
    equipmentType: "Helmet (STR)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(760-960) Armor",
    valueRanges: [],
    rawAffix: "` +(760-960)` Armor",
  },
] as const satisfies readonly BaseGearAffix[];

export type HelmetStrBaseAffixAffix =
  (typeof HELMET_STR_BASE_AFFIX_AFFIXES)[number];
