import { BaseGearAffix } from "./types";

export const MUSKET_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Musket",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(12-15)% chance for Attacks to cause Ailment",
    valueRanges: [],
    rawAffix: "` +(12-15)`% chance for Attacks to cause Ailment",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Musket",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-25)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(15-25)`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Musket",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(3-6)% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +(3-6)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Musket",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(40-45)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(40-45)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Musket",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(5-8)% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +(5-8)`% gear Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Musket",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(6-12)% chance to gain 1 stack of Agility Blessing on defeat",
    valueRanges: [],
    rawAffix:
      "` +(6-12)`% chance to gain 1 stack of Agility Blessing on defeat",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Musket",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Adds  (7-10) -  (14-17) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (7-10)` - ` (14-17)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Musket",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Adds  (7-12)% of Elemental Damage as Erosion Damage",
    valueRanges: [],
    rawAffix: "Adds ` (7-12)`% of Elemental Damage as Erosion Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Musket",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Damage Penetrates  (8-12)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "Damage Penetrates ` (8-12)`% Elemental Resistance",
  },
] as const satisfies readonly BaseGearAffix[];

export type MusketCorrosionBaseAffix =
  (typeof MUSKET_CORROSION_BASE_AFFIXES)[number];
