import { BaseGearAffix } from "./types";

export const NECKLACE_BASE_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Immune to Frostbite",
    valueRanges: [],
    rawAffix: "Immune to Frostbite",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  20 Biting Cold Curse upon inflicting damage. Cooldown:  0.2 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` 20` Biting Cold Curse upon inflicting damage. Cooldown: ` 0.2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  20 Corruption Curse upon inflicting damage. Cooldown:  0.2 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` 20` Corruption Curse upon inflicting damage. Cooldown: ` 0.2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  20 Electrocute Curse upon inflicting damage. Cooldown:  0.2 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` 20` Electrocute Curse upon inflicting damage. Cooldown: ` 0.2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  20 Vulnerability Curse upon inflicting damage. Cooldown:  0.2 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` 20` Vulnerability Curse upon inflicting damage. Cooldown: ` 0.2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  20 Scorch Curse upon inflicting damage. Cooldown:  0.2 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` 20` Scorch Curse upon inflicting damage. Cooldown: ` 0.2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(11-15)% Movement Speed",
    valueRanges: [],
    rawAffix: "` +(11-15)`% Movement Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(2-3)% damage per stack of any Blessing",
    valueRanges: [],
    rawAffix: "` +(2-3)`% damage per stack of any Blessing",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(26-30)% chance to avoid Elemental Ailments",
    valueRanges: [],
    rawAffix: "` +(26-30)`% chance to avoid Elemental Ailments",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +1% damage per  27 stats",
    valueRanges: [],
    rawAffix: "` +1`% damage per ` 27` stats",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "Adds  10 Base Ailment Damage",
    valueRanges: [],
    rawAffix: "Adds ` 10` Base Ailment Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Dexterity",
    valueRanges: [],
    rawAffix: "` +(15-20)` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Intelligence",
    valueRanges: [],
    rawAffix: "` +(15-20)` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Strength",
    valueRanges: [],
    rawAffix: "` +(15-20)` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% damage\n+(20-24)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% damage<> ` +(20-24)`% Minion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(3-4)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(3-4)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(54-74) Max Life",
    valueRanges: [],
    rawAffix: "` +(54-74)` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(87-117) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(87-117)` Max Energy Shield",
  },
] as const satisfies readonly BaseGearAffix[];

export type NecklaceBaseAffixAffix =
  (typeof NECKLACE_BASE_AFFIX_AFFIXES)[number];
