import { BaseGearAffix } from "./types";

export const NECKLACE_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(10-15)% Sealed Mana Compensation for Charged Flames",
    valueRanges: [],
    rawAffix: "` +(10-15)`% Sealed Mana Compensation for Charged Flames",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(10-15)% Sealed Mana Compensation for Deep Pain",
    valueRanges: [],
    rawAffix: "` +(10-15)`% Sealed Mana Compensation for Deep Pain",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(10-15)% Sealed Mana Compensation for Electric Conversion",
    valueRanges: [],
    rawAffix: "` +(10-15)`% Sealed Mana Compensation for Electric Conversion",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(10-15)% Sealed Mana Compensation for Frigid Domain",
    valueRanges: [],
    rawAffix: "` +(10-15)`% Sealed Mana Compensation for Frigid Domain",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(10-15)% Sealed Mana Compensation for Weapon Amplification",
    valueRanges: [],
    rawAffix: "` +(10-15)`% Sealed Mana Compensation for Weapon Amplification",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-20)% Skill Effect Duration",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Skill Effect Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(30-40)% Skill Area",
    valueRanges: [],
    rawAffix: "` +(30-40)`% Skill Area",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(50-70)% damage",
    valueRanges: [],
    rawAffix: "` +(50-70)`% damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(60-80) Attack and Spell Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(60-80)` Attack and Spell Critical Strike Rating",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(8-10)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(8-10)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Immune to Ignite\nImmune to Numbed",
    valueRanges: [],
    rawAffix: "Immune to Ignite<> Immune to Numbed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Immune to Frostbite\nImmune to Numbed",
    valueRanges: [],
    rawAffix: "Immune to Frostbite<> Immune to Numbed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Immune to Elemental Ailments",
    valueRanges: [],
    rawAffix: "Immune to Elemental Ailments",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "You can cast  1 additional Curses",
    valueRanges: [],
    rawAffix: "You can cast ` 1` additional Curses",
  },
] as const satisfies readonly BaseGearAffix[];

export type NecklaceCorrosionBaseAffix =
  (typeof NECKLACE_CORROSION_BASE_AFFIXES)[number];
