import { BaseGearAffix } from "./types";

export const NECKLACE_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+12Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+12Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+12Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+18Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+18Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+18Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+24Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+24Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+24Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+3Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+3Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+3Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+5Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+5Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+5Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+8Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+8Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+8Strength",
  },
] as const satisfies readonly BaseGearAffix[];

export type NecklaceBaseStatsAffix =
  (typeof NECKLACE_BASE_STATS_AFFIXES)[number];
