import { BaseGearAffix } from "./types";

export const NECKLACE_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(21-26)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(21-26)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(21-26)% Aura Effect",
    valueRanges: [],
    rawAffix: "` +(21-26)`% Aura Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(33-42)% additional Deterioration Duration",
    valueRanges: [],
    rawAffix: "` +(33-42)`% additional Deterioration Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(37-54)% Freeze Duration",
    valueRanges: [],
    rawAffix: "` +(37-54)`% Freeze Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(7-8)% damage per stack of any Blessing",
    valueRanges: [],
    rawAffix: "` +(7-8)`% damage per stack of any Blessing",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +1% damage per  8 stats",
    valueRanges: [],
    rawAffix: "` +1`% damage per ` 8` stats",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(15-20)% Sealed Mana Compensation",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(15-20)% Aura Effect",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Aura Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(23-32)% additional Deterioration Duration",
    valueRanges: [],
    rawAffix: "` +(23-32)`% additional Deterioration Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(28-36)% Freeze Duration",
    valueRanges: [],
    rawAffix: "` +(28-36)`% Freeze Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(5-6)% damage per stack of any Blessing",
    valueRanges: [],
    rawAffix: "` +(5-6)`% damage per stack of any Blessing",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +1% damage per  12 stats",
    valueRanges: [],
    rawAffix: "` +1`% damage per ` 12` stats",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(11-13)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(11-13)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(11-13)% all stats",
    valueRanges: [],
    rawAffix: "` +(11-13)`% all stats",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(19-23)% Blessing Duration",
    valueRanges: [],
    rawAffix: "` +(19-23)`% Blessing Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(25-31)% Attack and Cast Speed\n+(25-31)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(25-31)`% Attack and Cast Speed<> ` +(25-31)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " 100% chance to gain a Barrier for every  5 m you move\n+25% Barrier Shield",
    valueRanges: [],
    rawAffix:
      "` 100`% chance to gain a Barrier for every ` 5` m you move<> ` +25`% Barrier Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " 80% chance to gain  1 charge stacks when using a Terra Skill",
    valueRanges: [],
    rawAffix:
      "` 80`% chance to gain ` 1` charge stacks when using a Terra Skill",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(14-18)% Blessing Duration",
    valueRanges: [],
    rawAffix: "` +(14-18)`% Blessing Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(18-24)% Attack and Cast Speed\n+(18-24)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(18-24)`% Attack and Cast Speed<> ` +(18-24)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(42-60)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(42-60)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(8-10)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(8-10)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(8-10)% all stats",
    valueRanges: [],
    rawAffix: "` +(8-10)`% all stats",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " 100% chance to gain a Barrier for every  5 m you move",
    valueRanges: [],
    rawAffix: "` 100`% chance to gain a Barrier for every ` 5` m you move",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " 60% chance to gain  1 charge stacks when using a Terra Skill",
    valueRanges: [],
    rawAffix:
      "` 60`% chance to gain ` 1` charge stacks when using a Terra Skill",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(46-59)% Projectile Speed",
    valueRanges: [],
    rawAffix: "` +(46-59)`% Projectile Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(33-45)% Projectile Speed",
    valueRanges: [],
    rawAffix: "` +(33-45)`% Projectile Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type NecklaceSuffixAffix = (typeof NECKLACE_SUFFIX_AFFIXES)[number];
