import { BaseGearAffix } from "./types";

export const NECKLACE_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "[Beacon]  +2 Max Spell Burst",
    valueRanges: [],
    rawAffix: "[Beacon] ` +2` Max Spell Burst",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Multistrikes deal  (36-52)% increasing damage",
    valueRanges: [],
    rawAffix: "Multistrikes deal ` (36-52)`% increasing damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(51-65)% Deterioration Damage",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Deterioration Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +3 Active Skill Level",
    valueRanges: [],
    rawAffix: "` +3` Active Skill Level",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +3 Minion Skill Level",
    valueRanges: [],
    rawAffix: "` +3` Minion Skill Level",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Have Fervor\n+5% additional damage",
    valueRanges: [],
    rawAffix: "Have Fervor<> ` +5`% additional damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Multistrikes deal  (28-40)% increasing damage",
    valueRanges: [],
    rawAffix: "Multistrikes deal ` (28-40)`% increasing damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(1-2) Active Skill Level",
    valueRanges: [],
    rawAffix: "` +(1-2)` Active Skill Level",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(36-50)% Deterioration Damage",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Deterioration Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +1 Max Spell Burst",
    valueRanges: [],
    rawAffix: "` +1` Max Spell Burst",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +2 Minion Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Minion Skill Level",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Have Fervor",
    valueRanges: [],
    rawAffix: "Have Fervor",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(21-26)% Defense",
    valueRanges: [],
    rawAffix: "` +(21-26)`% Defense",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(31-39)% Sealed Mana Compensation for Energy Fortress",
    valueRanges: [],
    rawAffix: "` +(31-39)`% Sealed Mana Compensation for Energy Fortress",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(31-39)% Sealed Mana Compensation for Nimbleness",
    valueRanges: [],
    rawAffix: "` +(31-39)`% Sealed Mana Compensation for Nimbleness",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(31-39)% Sealed Mana Compensation for Steadfast",
    valueRanges: [],
    rawAffix: "` +(31-39)`% Sealed Mana Compensation for Steadfast",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(33-42)% Deterioration Chance",
    valueRanges: [],
    rawAffix: "` +(33-42)`% Deterioration Chance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(49-62) initial Growth for Spirit Magi",
    valueRanges: [],
    rawAffix: "` +(49-62)` initial Growth for Spirit Magi",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Dexterity",
    valueRanges: [],
    rawAffix: "` +(61-78)` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Intelligence",
    valueRanges: [],
    rawAffix: "` +(61-78)` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Strength",
    valueRanges: [],
    rawAffix: "` +(61-78)` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      "Gains Attack Aggression when casting an Attack Skill\n+(40-60)% Attack Aggression Effect",
    valueRanges: [],
    rawAffix:
      "Gains Attack Aggression when casting an Attack Skill<> ` +(40-60)`% Attack Aggression Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      "Gains Spell Aggression when casting a Spell Skill\n+(40-60)% Spell Aggression Effect",
    valueRanges: [],
    rawAffix:
      "Gains Spell Aggression when casting a Spell Skill<> ` +(40-60)`% Spell Aggression Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(15-20)% Defense",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Defense",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(22-30)% Sealed Mana Compensation for Energy Fortress",
    valueRanges: [],
    rawAffix: "` +(22-30)`% Sealed Mana Compensation for Energy Fortress",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(22-30)% Sealed Mana Compensation for Nimbleness",
    valueRanges: [],
    rawAffix: "` +(22-30)`% Sealed Mana Compensation for Nimbleness",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(22-30)% Sealed Mana Compensation for Steadfast",
    valueRanges: [],
    rawAffix: "` +(22-30)`% Sealed Mana Compensation for Steadfast",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(23-32)% Deterioration Chance",
    valueRanges: [],
    rawAffix: "` +(23-32)`% Deterioration Chance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(35-48) initial Growth for Spirit Magi",
    valueRanges: [],
    rawAffix: "` +(35-48)` initial Growth for Spirit Magi",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Dexterity",
    valueRanges: [],
    rawAffix: "` +(43-60)` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Intelligence",
    valueRanges: [],
    rawAffix: "` +(43-60)` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Strength",
    valueRanges: [],
    rawAffix: "` +(43-60)` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      "Gains Attack Aggression when casting an Attack Skill\n+(10-30)% Attack Aggression Effect",
    valueRanges: [],
    rawAffix:
      "Gains Attack Aggression when casting an Attack Skill<> ` +(10-30)`% Attack Aggression Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      "Gains Spell Aggression when casting a Spell Skill\n+(10-30)% Spell Aggression Effect",
    valueRanges: [],
    rawAffix:
      "Gains Spell Aggression when casting a Spell Skill<> ` +(10-30)`% Spell Aggression Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156) Max Mana",
    valueRanges: [],
    rawAffix: "` +(121-156)` Max Mana",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(221-286) Max Life",
    valueRanges: [],
    rawAffix: "` +(221-286)` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(319-455) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(319-455)` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(37-47)% Armor",
    valueRanges: [],
    rawAffix: "` +(37-47)`% Armor",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(37-47)% Evasion",
    valueRanges: [],
    rawAffix: "` +(37-47)`% Evasion",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(66-94)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(66-94)`% Minion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(155-220) Max Life",
    valueRanges: [],
    rawAffix: "` +(155-220)` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(245-350) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(245-350)` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(27-36)% Armor",
    valueRanges: [],
    rawAffix: "` +(27-36)`% Armor",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(27-36)% Evasion",
    valueRanges: [],
    rawAffix: "` +(27-36)`% Evasion",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(51-72)`% Minion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(85-120) Max Mana",
    valueRanges: [],
    rawAffix: "` +(85-120)` Max Mana",
  },
] as const satisfies readonly BaseGearAffix[];

export type NecklacePrefixAffix = (typeof NECKLACE_PREFIX_AFFIXES)[number];
