import { BaseGearAffix } from "./types";

export const NECKLACE_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: "",
    valueRanges: [],
    rawAffix: "",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +12 Dexterity",
    valueRanges: [],
    rawAffix: "` +12` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +12 Intelligence",
    valueRanges: [],
    rawAffix: "` +12` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +12 Strength",
    valueRanges: [],
    rawAffix: "` +12` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +18 Dexterity",
    valueRanges: [],
    rawAffix: "` +18` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +18 Intelligence",
    valueRanges: [],
    rawAffix: "` +18` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +18 Strength",
    valueRanges: [],
    rawAffix: "` +18` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +24 Dexterity",
    valueRanges: [],
    rawAffix: "` +24` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +24 Intelligence",
    valueRanges: [],
    rawAffix: "` +24` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +24 Strength",
    valueRanges: [],
    rawAffix: "` +24` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +3 Dexterity",
    valueRanges: [],
    rawAffix: "` +3` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +3 Intelligence",
    valueRanges: [],
    rawAffix: "` +3` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +3 Strength",
    valueRanges: [],
    rawAffix: "` +3` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +5 Dexterity",
    valueRanges: [],
    rawAffix: "` +5` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +5 Intelligence",
    valueRanges: [],
    rawAffix: "` +5` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +5 Strength",
    valueRanges: [],
    rawAffix: "` +5` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +8 Dexterity",
    valueRanges: [],
    rawAffix: "` +8` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +8 Intelligence",
    valueRanges: [],
    rawAffix: "` +8` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Necklace",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +8 Strength",
    valueRanges: [],
    rawAffix: "` +8` Strength",
  },
] as const satisfies readonly BaseGearAffix[];

export type NecklaceBaseStatsAffix =
  (typeof NECKLACE_BASE_STATS_AFFIXES)[number];
