import { BaseGearAffix } from "./types";

export const ONE_HANDED_AXE_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(10-15)% Skill Area",
    valueRanges: [],
    rawAffix: "` +(10-15)`% Skill Area",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-25)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(15-25)`% gear Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(25-30)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(25-30)`% Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(3-6)% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +(3-6)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(4-8)% chance to gain 1 stack of Tenacity Blessing on defeat",
    valueRanges: [],
    rawAffix:
      "` +(4-8)`% chance to gain 1 stack of Tenacity Blessing on defeat",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(5-8)% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +(5-8)`% gear Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Adds  (2-4) -  (8-10) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (2-4)` - ` (8-10)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Eliminates enemies under  (5-8)% Life upon inflicting damage",
    valueRanges: [],
    rawAffix: "Eliminates enemies under ` (5-8)`% Life upon inflicting damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template:
      "Enemies have a  30% chance to explode when defeated, dealing Secondary Physical Damage equal to  (5-10)% of their Max Life to enemies within a 5m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a ` 30`% chance to explode when defeated, dealing Secondary Physical Damage equal to ` (5-10)`% of their Max Life to enemies within a 5m radius",
  },
] as const satisfies readonly BaseGearAffix[];

export type OneHandedAxeCorrosionBaseAffix =
  (typeof ONE_HANDED_AXE_CORROSION_BASE_AFFIXES)[number];
