import { BaseGearAffix } from "./types";

export const ONE_HANDED_SWORD_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Shadow Quantity  +2 \n+(10-15)% additional Shadow Damage",
    valueRanges: [],
    rawAffix: "Shadow Quantity ` +2` <> ` +(10-15)`% additional Shadow Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(41-52)% chance to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(41-52)`% chance to deal Double Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(48-60)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(48-60)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(54-69)% additional damage against Frozen enemies",
    valueRanges: [],
    rawAffix: "` +(54-69)`% additional damage against Frozen enemies",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(55-65)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(55-65)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +30% Steep Strike chance.\n+(23-29)% additional Steep Strike Damage",
    valueRanges: [],
    rawAffix:
      "` +30`% Steep Strike chance.<> ` +(23-29)`% additional Steep Strike Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Adds  30% of Main-Hand Weapon Damage to Base Ignite Damage",
    valueRanges: [],
    rawAffix: "Adds ` 30`% of Main-Hand Weapon Damage to Base Ignite Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Shadow Quantity  +2 \n-5% additional Shadow Damage",
    valueRanges: [],
    rawAffix: "Shadow Quantity ` +2` <> ` -5`% additional Shadow Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(29-40)% chance to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(29-40)`% chance to deal Double Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(35-45)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(35-45)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(38-53)% additional damage against Frozen enemies",
    valueRanges: [],
    rawAffix: "` +(38-53)`% additional damage against Frozen enemies",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(40-50)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(40-50)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +23% Steep Strike chance.\n+(16-22)% additional Steep Strike Damage",
    valueRanges: [],
    rawAffix:
      "` +23`% Steep Strike chance.<> ` +(16-22)`% additional Steep Strike Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Adds  24% of Main-Hand Weapon Damage to Base Ignite Damage",
    valueRanges: [],
    rawAffix: "Adds ` 24`% of Main-Hand Weapon Damage to Base Ignite Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(166-234)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(166-234)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(33-47)% Attack and Cast Speed\n+(33-47)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(33-47)`% Attack and Cast Speed<> ` +(33-47)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(47-64)% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +(47-64)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(60-70)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(60-70)`% Focus Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(73-94)% chance to Multistrike",
    valueRanges: [],
    rawAffix: "` +(73-94)`% chance to Multistrike",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(76-98)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(76-98)`% Affliction Effect",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(91-117)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(128-180)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(128-180)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(26-36)% Attack and Cast Speed\n+(26-36)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(26-36)`% Attack and Cast Speed<> ` +(26-36)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(36-50)% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(45-54)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(45-54)`% Focus Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(52-72)% chance to Multistrike",
    valueRanges: [],
    rawAffix: "` +(52-72)`% chance to Multistrike",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(54-75)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(54-75)`% Affliction Effect",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(64-90)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Erosion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(19-23)% Energy Shield Regain",
    valueRanges: [],
    rawAffix: "` +(19-23)`% Energy Shield Regain",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(19-23)% Life Regain",
    valueRanges: [],
    rawAffix: "` +(19-23)`% Life Regain",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(29-41)% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +(29-41)`% gear Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(14-18)% Energy Shield Regain",
    valueRanges: [],
    rawAffix: "` +(14-18)`% Energy Shield Regain",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(14-18)% Life Regain",
    valueRanges: [],
    rawAffix: "` +(14-18)`% Life Regain",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(23-32)% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +(23-32)`% gear Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Erosion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Physical Damage",
  },
] as const satisfies readonly BaseGearAffix[];

export type OneHandedSwordSuffixAffix =
  (typeof ONE_HANDED_SWORD_SUFFIX_AFFIXES)[number];
