import { BaseGearAffix } from "./types";

export const ONE_HANDED_AXE_SWEET_DREAM_AFFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Agility Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Agility Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Focus Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Tenacity Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Tenacity Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(5-7)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(5-7)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% additional damage against Traumatized enemies",
    valueRanges: [],
    rawAffix: "` +(6-8)`% additional damage against Traumatized enemies",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-9)% additional Steep Strike Damage",
    valueRanges: [],
    rawAffix: "` +(6-9)`% additional Steep Strike Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Erosion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Melee Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Melee Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(6-8)% Attack Speed",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (1-2) -  (28-32) Lightning Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (1-2)` - ` (28-32)` Lightning Damage to Attacks",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (10-13) -  (14-19) Cold Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (10-13)` - ` (14-19)` Cold Damage to Attacks",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (10-13) -  (14-19) Physical Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (10-13)` - ` (14-19)` Physical Damage to Attacks",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (11-13) -  (15-18) Erosion Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (11-13)` - ` (15-18)` Erosion Damage to Attacks",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Axe",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (9-14) -  (15-20) Fire Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (9-14)` - ` (15-20)` Fire Damage to Attacks",
  },
] as const satisfies readonly BaseGearAffix[];

export type OneHandedAxeSweetDreamAffixAffix =
  (typeof ONE_HANDED_AXE_SWEET_DREAM_AFFIX_AFFIXES)[number];
