import { BaseGearAffix } from "./types";

export const ONE_HANDED_SWORD_TOWER_SEQUENCE_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      " +120% Fearless Aura\n-20% additional Fearless Sealed Mana Compensation",
    valueRanges: [],
    rawAffix:
      "` +120`% Fearless Aura<> ` -20`% additional Fearless Sealed Mana Compensation",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      " +15% additional Deterioration Damage\n10% chance to inflict  1 additional stack(s) of Deterioration",
    valueRanges: [],
    rawAffix:
      "` +15`% additional Deterioration Damage<> ` 10`% chance to inflict ` 1` additional stack(s) of Deterioration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: " +25% Elemental Damage for the gear\n-25% gear Physical Damage",
    valueRanges: [],
    rawAffix:
      "` +25`% Elemental Damage for the gear<> ` -25`% gear Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      " +80% gear Physical Damage\n-20% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix:
      "` +80`% gear Physical Damage<> ` -20`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Adds  1 -  1 Physical Damage to Attacks per  2260 Armor",
    valueRanges: [],
    rawAffix: "Adds ` 1` - ` 1` Physical Damage to Attacks per ` 2260` Armor",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Adds  1 -  3 Lightning Damage to Attacks per  10 Dexterity",
    valueRanges: [],
    rawAffix:
      "Adds ` 1` - ` 3` Lightning Damage to Attacks per ` 10` Dexterity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Adds  2 -  2 Fire Damage to Attacks per  10 Strength",
    valueRanges: [],
    rawAffix: "Adds ` 2` - ` 2` Fire Damage to Attacks per ` 10` Strength",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Enemies have a  15% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to  25% of their Max Life to enemies within a  5 m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a ` 15`% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to ` 25`% of their Max Life to enemies within a ` 5` m radius",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Main Skill is supported by Lv.  25 Steamroll",
    valueRanges: [],
    rawAffix: "Main Skill is supported by Lv. ` 25` Steamroll",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +10% all stats",
    valueRanges: [],
    rawAffix: "` +10`% all stats",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +10% additional damage on Critical Strike",
    valueRanges: [],
    rawAffix: "` +10`% additional damage on Critical Strike",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +20% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +20`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +6% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +6`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% additional damage for Weapons",
    valueRanges: [],
    rawAffix: "` +8`% additional damage for Weapons",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% Cold Penetration",
    valueRanges: [],
    rawAffix: "` +8`% Cold Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +8`% Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% Fire Penetration",
    valueRanges: [],
    rawAffix: "` +8`% Fire Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +8`% gear Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "One-Handed Sword",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% Lightning Penetration",
    valueRanges: [],
    rawAffix: "` +8`% Lightning Penetration",
  },
] as const satisfies readonly BaseGearAffix[];

export type OneHandedSwordTowerSequenceAffix =
  (typeof ONE_HANDED_SWORD_TOWER_SEQUENCE_AFFIXES)[number];
