import { BaseGearAffix } from "./types";

export const RING_SWEET_DREAM_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Adds  (18-20)% of Physical Damage as Erosion Damage",
    valueRanges: [],
    rawAffix: "Adds ` (18-20)`% of Physical Damage as Erosion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Adds  (18-20)% of Physical Damage as Fire Damage",
    valueRanges: [],
    rawAffix: "Adds ` (18-20)`% of Physical Damage as Fire Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Adds  (18-20)% of Physical Damage as Lightning Damage",
    valueRanges: [],
    rawAffix: "Adds ` (18-20)`% of Physical Damage as Lightning Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Adds  (18-20)% of Physical Damage to Cold Damage",
    valueRanges: [],
    rawAffix: "Adds ` (18-20)`% of Physical Damage to Cold Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Agility Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Agility Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Focus Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Tenacity Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Tenacity Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  20 Frost Touch Curse upon inflicting damage. Cooldown:  0.2 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` 20` Frost Touch Curse upon inflicting damage. Cooldown: ` 0.2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  20 Blind Curse upon inflicting damage. Cooldown:  0.2 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` 20` Blind Curse upon inflicting damage. Cooldown: ` 0.2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  20 Timid Curse upon inflicting damage. Cooldown:  0.2 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` 20` Timid Curse upon inflicting damage. Cooldown: ` 0.2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Triggers Lv.  20 Entangled Pain Curse upon inflicting damage. Cooldown:  0.2 s",
    valueRanges: [],
    rawAffix:
      "Triggers Lv. ` 20` Entangled Pain Curse upon inflicting damage. Cooldown: ` 0.2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(11-15)% Movement Speed",
    valueRanges: [],
    rawAffix: "` +(11-15)`% Movement Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(15-20)% Fervor effect",
    valueRanges: [],
    rawAffix: "` +(15-20)`% Fervor effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +(20-25)% chance to launch one more wave when casting a Barrage Skill",
    valueRanges: [],
    rawAffix:
      "` +(20-25)`% chance to launch one more wave when casting a Barrage Skill",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      "Inflicts Cold Infiltration when dealing damage. Interval for each enemy:  2 s",
    valueRanges: [],
    rawAffix:
      "Inflicts Cold Infiltration when dealing damage. Interval for each enemy: ` 2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      "When dealing damage, inflicts Fire Infiltration . Interval for each enemy:  2 s",
    valueRanges: [],
    rawAffix:
      "When dealing damage, inflicts Fire Infiltration . Interval for each enemy: ` 2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template:
      "When dealing damage, inflicts Lightning Infiltration . Interval for each enemy:  2 s",
    valueRanges: [],
    rawAffix:
      "When dealing damage, inflicts Lightning Infiltration . Interval for each enemy: ` 2` s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Dexterity",
    valueRanges: [],
    rawAffix: "` +(15-20)` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Intelligence",
    valueRanges: [],
    rawAffix: "` +(15-20)` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Strength",
    valueRanges: [],
    rawAffix: "` +(15-20)` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(54-74) Max Life",
    valueRanges: [],
    rawAffix: "` +(54-74)` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(6-8)% Attack and Cast Speed",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Attack and Cast Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(87-117) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(87-117)` Max Energy Shield",
  },
] as const satisfies readonly BaseGearAffix[];

export type RingSweetDreamAffixAffix =
  (typeof RING_SWEET_DREAM_AFFIX_AFFIXES)[number];
