import { BaseGearAffix } from "./types";

export const RING_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(13-16)% Elemental Resistance\n+(13-16)% Erosion Resistance",
    valueRanges: [],
    rawAffix:
      "` +(13-16)`% Elemental Resistance<> ` +(13-16)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(25-30)% additional damage for Main-Hand Weapons",
    valueRanges: [],
    rawAffix: "` +(25-30)`% additional damage for Main-Hand Weapons",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(27-34)% chance to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(27-34)`% chance to deal Double Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(33-42)% additional Deterioration Duration",
    valueRanges: [],
    rawAffix: "` +(33-42)`% additional Deterioration Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(37-54)% Freeze Duration",
    valueRanges: [],
    rawAffix: "` +(37-54)`% Freeze Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(51-65)% Fervor effect",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Fervor effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(84-108)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(84-108)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(18-23)% additional damage for Main-Hand Weapons",
    valueRanges: [],
    rawAffix: "` +(18-23)`% additional damage for Main-Hand Weapons",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(19-26)% chance to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(19-26)`% chance to deal Double Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(23-32)% additional Deterioration Duration",
    valueRanges: [],
    rawAffix: "` +(23-32)`% additional Deterioration Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(28-36)% Freeze Duration",
    valueRanges: [],
    rawAffix: "` +(28-36)`% Freeze Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(36-50)% Fervor effect",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Fervor effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(59-83)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(59-83)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(9-12)% Elemental Resistance\n+(9-12)% Erosion Resistance",
    valueRanges: [],
    rawAffix:
      "` +(9-12)`% Elemental Resistance<> ` +(9-12)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(33-42)% Max Mana",
    valueRanges: [],
    rawAffix: "` +(33-42)`% Max Mana",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(37-47)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(37-47)`% Focus Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(46-65)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(46-65)`% Reaping Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(51-65)% Terra Charge Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Terra Charge Recovery Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(51-65)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Affliction Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +1 Combo Points gained from Combo Starters\n+(3-5)% additional damage",
    valueRanges: [],
    rawAffix:
      "` +1` Combo Points gained from Combo Starters<> ` +(3-5)`% additional damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " 100% chance to gain a Barrier for every  5 m you move\n+25% Barrier Shield",
    valueRanges: [],
    rawAffix:
      "` 100`% chance to gain a Barrier for every ` 5` m you move<> ` +25`% Barrier Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      "Inflicts  (6-8) Frostbite Rating to Frostbitten enemies every second",
    valueRanges: [],
    rawAffix:
      "Inflicts ` (6-8)` Frostbite Rating to Frostbitten enemies every second",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(23-32)% Max Mana",
    valueRanges: [],
    rawAffix: "` +(23-32)`% Max Mana",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(26-36)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(26-36)`% Focus Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(35-50)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(35-50)`% Reaping Duration",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(36-50)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Affliction Effect",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(37-50)% Terra Charge Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(37-50)`% Terra Charge Recovery Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(44-60)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(44-60)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +1 Combo Points gained from Combo Starters\n+(1-2)% additional damage",
    valueRanges: [],
    rawAffix:
      "` +1` Combo Points gained from Combo Starters<> ` +(1-2)`% additional damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " 100% chance to gain a Barrier for every  5 m you move",
    valueRanges: [],
    rawAffix: "` 100`% chance to gain a Barrier for every ` 5` m you move",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      "Inflicts  5 Frostbite Rating to Frostbitten enemies every second",
    valueRanges: [],
    rawAffix:
      "Inflicts ` 5` Frostbite Rating to Frostbitten enemies every second",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(121-156)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(38-48)% Frostbite inflicted",
    valueRanges: [],
    rawAffix: "` +(38-48)`% Frostbite inflicted",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(27-37)% Frostbite inflicted",
    valueRanges: [],
    rawAffix: "` +(27-37)`% Frostbite inflicted",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(87-120)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(87-120)`% Critical Strike Rating",
  },
] as const satisfies readonly BaseGearAffix[];

export type RingSuffixAffix = (typeof RING_SUFFIX_AFFIXES)[number];
