import { BaseGearAffix } from "./types";

export const ROD_PREFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(26-36)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix: "` +(26-36)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(28-39)% Elemental and Erosion Resistance Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(28-39)`% Elemental and Erosion Resistance Penetration for Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(3-4) Main Skill Level",
    valueRanges: [],
    rawAffix: "` +(3-4)` Main Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(3-4) Minion Skill Level",
    valueRanges: [],
    rawAffix: "` +(3-4)` Minion Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(18-25)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix: "` +(18-25)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(22-30)% Elemental and Erosion Resistance Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(22-30)`% Elemental and Erosion Resistance Penetration for Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +3 Main Skill Level",
    valueRanges: [],
    rawAffix: "` +3` Main Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +3 Minion Skill Level",
    valueRanges: [],
    rawAffix: "` +3` Minion Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Dexterity",
    valueRanges: [],
    rawAffix: "` +(91-117)` Dexterity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Intelligence",
    valueRanges: [],
    rawAffix: "` +(91-117)` Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Strength",
    valueRanges: [],
    rawAffix: "` +(91-117)` Strength",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +1 to Max Summonable Synthetic Troops\n+(10-12)% additional Minion Damage",
    valueRanges: [],
    rawAffix:
      "` +1` to Max Summonable Synthetic Troops<> ` +(10-12)`% additional Minion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Spirit Magi  +(31-39)% chance to use an Enhanced Skill",
    valueRanges: [],
    rawAffix: "Spirit Magi ` +(31-39)`% chance to use an Enhanced Skill",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Dexterity",
    valueRanges: [],
    rawAffix: "` +(64-90)` Dexterity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Intelligence",
    valueRanges: [],
    rawAffix: "` +(64-90)` Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Strength",
    valueRanges: [],
    rawAffix: "` +(64-90)` Strength",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +1 to Max Summonable Synthetic Troops\n+(6-8)% additional Minion Damage",
    valueRanges: [],
    rawAffix:
      "` +1` to Max Summonable Synthetic Troops<> ` +(6-8)`% additional Minion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Spirit Magi  +(22-30)% chance to use an Enhanced Skill",
    valueRanges: [],
    rawAffix: "Spirit Magi ` +(22-30)`% chance to use an Enhanced Skill",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Minion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(46-59)% Minion Max Life",
    valueRanges: [],
    rawAffix: "` +(46-59)`% Minion Max Life",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (82-84) -  (106-113) Fire Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (82-84)` - ` (106-113)` Fire Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (83-85) -  (110-112) Cold Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (83-85)` - ` (110-112)` Cold Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (87-89) -  (106-108) Erosion Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (87-89)` - ` (106-108)` Erosion Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (87-89) -  (106-108) Physical Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (87-89)` - ` (106-108)` Physical Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (9-11) -  (184-186) Lightning Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (9-11)` - ` (184-186)` Lightning Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(33-45)% Minion Max Life",
    valueRanges: [],
    rawAffix: "` +(33-45)`% Minion Max Life",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Minion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (63-65) -  (82-87) Fire Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (63-65)` - ` (82-87)` Fire Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (64-66) -  (85-87) Cold Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (64-66)` - ` (85-87)` Cold Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (67-69) -  (82-84) Erosion Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (67-69)` - ` (82-84)` Erosion Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (67-69) -  (82-84) Physical Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (67-69)` - ` (82-84)` Physical Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (7-9) -  (142-144) Lightning Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (7-9)` - ` (142-144)` Lightning Damage to Minions",
  },
] as const satisfies readonly BaseGearAffix[];

export type RodPrefixAffix = (typeof ROD_PREFIX_AFFIXES)[number];
