import { BaseGearAffix } from "./types";

export const ROD_BASE_AFFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Focus Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(5-7)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix: "` +(5-7)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% additional Minion Damage",
    valueRanges: [],
    rawAffix: "` +(6-8)`% additional Minion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +100% chance to gain 1 stack of Focus Blessing when casting a Summon Skill. Interval:  1 s",
    valueRanges: [],
    rawAffix:
      "` +100`% chance to gain 1 stack of Focus Blessing when casting a Summon Skill. Interval: ` 1` s",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template:
      " +100% chance to gain 1 stack of Tenacity Blessing when casting a skill. Interval:  1 s",
    valueRanges: [],
    rawAffix:
      "` +100`% chance to gain 1 stack of Tenacity Blessing when casting a skill. Interval: ` 1` s",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "Minion Damage penetrates  (6-8)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "Minion Damage penetrates ` (6-8)`% Elemental Resistance",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Dexterity",
    valueRanges: [],
    rawAffix: "` +(15-20)` Dexterity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Intelligence",
    valueRanges: [],
    rawAffix: "` +(15-20)` Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(15-20) Strength",
    valueRanges: [],
    rawAffix: "` +(15-20)` Strength",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Minion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(6-8)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (1-2) -  (28-32) Lightning Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (1-2)` - ` (28-32)` Lightning Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (10-13) -  (14-19) Cold Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (10-13)` - ` (14-19)` Cold Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (10-13) -  (14-19) Physical Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (10-13)` - ` (14-19)` Physical Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (11-13) -  (15-18) Erosion Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (11-13)` - ` (15-18)` Erosion Damage to Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (9-14) -  (15-20) Fire Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (9-14)` - ` (15-20)` Fire Damage to Minions",
  },
] as const satisfies readonly BaseGearAffix[];

export type RodBaseAffixAffix = (typeof ROD_BASE_AFFIX_AFFIXES)[number];
