import { BaseGearAffix } from "./types";

export const ROD_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(10-16)% Cast Speed",
    valueRanges: [],
    rawAffix: "` +(10-16)`% Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(20-30)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(20-30)`% Minion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(25-32)% Minion Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(25-32)`% Minion Critical Strike Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(30-40)% Minion Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(30-40)`% Minion Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(4-8)% chance to gain 1 stack of Focus Blessing on defeat",
    valueRanges: [],
    rawAffix: "` +(4-8)`% chance to gain 1 stack of Focus Blessing on defeat",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template:
      " +(5-8)% chance to trigger the Main Spell Skill 1 additional time when using it",
    valueRanges: [],
    rawAffix:
      "` +(5-8)`% chance to trigger the Main Spell Skill 1 additional time when using it",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template:
      " +(5-8)% Elemental and Erosion Resistance Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(5-8)`% Elemental and Erosion Resistance Penetration for Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(6-10)% Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(6-10)`% Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Adds  (5-8)% of Elemental Damage as Erosion Damage",
    valueRanges: [],
    rawAffix: "Adds ` (5-8)`% of Elemental Damage as Erosion Damage",
  },
] as const satisfies readonly BaseGearAffix[];

export type RodCorrosionBaseAffix = (typeof ROD_CORROSION_BASE_AFFIXES)[number];
