import { BaseGearAffix } from "./types";

export const ROD_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type RodBaseStatsAffix = (typeof ROD_BASE_STATS_AFFIXES)[number];
