import { BaseGearAffix } from "./types";

export const ROD_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(151-195)% Minion Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(151-195)`% Minion Critical Strike Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(36-46)% additional damage for Synthetic Troop Minions when having at least  40 Command",
    valueRanges: [],
    rawAffix:
      "` +(36-46)`% additional damage for Synthetic Troop Minions when having at least ` 40` Command",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(41-52)% additional Spirit Magus Enhanced Skill Damage and Ailment Damage dealt by Enhanced Skills",
    valueRanges: [],
    rawAffix:
      "` +(41-52)`% additional Spirit Magus Enhanced Skill Damage and Ailment Damage dealt by Enhanced Skills",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(41-52)% chance for Minions to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(41-52)`% chance for Minions to deal Double Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(61-78)% additional Spirit Magus Ultimate Damage and Ailment Damage dealt by Ultimate .",
    valueRanges: [],
    rawAffix:
      "` +(61-78)`% additional Spirit Magus Ultimate Damage and Ailment Damage dealt by Ultimate .",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(106-150)% Minion Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(106-150)`% Minion Critical Strike Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(26-35)% additional damage for Synthetic Troop Minions when having at least  40 Command",
    valueRanges: [],
    rawAffix:
      "` +(26-35)`% additional damage for Synthetic Troop Minions when having at least ` 40` Command",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(29-40)% additional Spirit Magus Enhanced Skill Damage and Ailment Damage dealt by Enhanced Skills",
    valueRanges: [],
    rawAffix:
      "` +(29-40)`% additional Spirit Magus Enhanced Skill Damage and Ailment Damage dealt by Enhanced Skills",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(29-40)% chance for Minions to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(29-40)`% chance for Minions to deal Double Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(43-60)% additional Spirit Magus Ultimate Damage and Ailment Damage dealt by Ultimate .",
    valueRanges: [],
    rawAffix:
      "` +(43-60)`% additional Spirit Magus Ultimate Damage and Ailment Damage dealt by Ultimate .",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(126-163) Minion Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(126-163)` Minion Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234)% Minion Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(181-234)`% Minion Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(73-94)% Minion Skill Area",
    valueRanges: [],
    rawAffix: "` +(73-94)`% Minion Skill Area",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180)% Minion Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(127-180)`% Minion Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(51-72)% Minion Skill Area",
    valueRanges: [],
    rawAffix: "` +(51-72)`% Minion Skill Area",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(89-125) Minion Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(89-125)` Minion Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Minion Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Minion Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Minion Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Minion Erosion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Physical Damage for Minions",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Physical Damage for Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-31)% Energy Shield Charge Speed",
    valueRanges: [],
    rawAffix: "` +(25-31)`% Energy Shield Charge Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template:
      " +(37-47)% Attack and Cast Speed\n+(37-47)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(37-47)`% Attack and Cast Speed<> ` +(37-47)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "Regenerates  (181-234) Life per second",
    valueRanges: [],
    rawAffix: "Regenerates ` (181-234)` Life per second",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(18-24)% Energy Shield Charge Speed",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Energy Shield Charge Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template:
      " +(27-36)% Attack and Cast Speed\n+(27-36)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(27-36)`% Attack and Cast Speed<> ` +(27-36)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Minion Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Minion Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Minion Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Minion Erosion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Physical Damage for Minions",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Physical Damage for Minions",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Rod",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "Regenerates  (130-180) Life per second",
    valueRanges: [],
    rawAffix: "Regenerates ` (130-180)` Life per second",
  },
] as const satisfies readonly BaseGearAffix[];

export type RodSuffixAffix = (typeof ROD_SUFFIX_AFFIXES)[number];
