import { BaseGearAffix } from "./types";

export const SCEPTER_PREFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " (31-39)% additional damage applied to Life",
    valueRanges: [],
    rawAffix: "` (31-39)`% additional damage applied to Life",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(28-39)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(28-39)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(3-4) Spell Skill Level",
    valueRanges: [],
    rawAffix: "` +(3-4)` Spell Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Terra Charge Stacks  +3 ",
    valueRanges: [],
    rawAffix: "Max Terra Charge Stacks ` +3` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " (22-30)% additional damage applied to Life",
    valueRanges: [],
    rawAffix: "` (22-30)`% additional damage applied to Life",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(22-30)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(22-30)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +3 Spell Skill Level",
    valueRanges: [],
    rawAffix: "` +3` Spell Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Terra Charge Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Terra Charge Stacks ` +2` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(2-3) Cold Skill Level",
    valueRanges: [],
    rawAffix: "` +(2-3)` Cold Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(2-3) Erosion Skill Level",
    valueRanges: [],
    rawAffix: "` +(2-3)` Erosion Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(2-3) Fire Skill Level",
    valueRanges: [],
    rawAffix: "` +(2-3)` Fire Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(2-3) Lightning Skill Level",
    valueRanges: [],
    rawAffix: "` +(2-3)` Lightning Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(2-3) Physical Skill Level",
    valueRanges: [],
    rawAffix: "` +(2-3)` Physical Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Dexterity",
    valueRanges: [],
    rawAffix: "` +(91-117)` Dexterity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Intelligence",
    valueRanges: [],
    rawAffix: "` +(91-117)` Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Strength",
    valueRanges: [],
    rawAffix: "` +(91-117)` Strength",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Dexterity",
    valueRanges: [],
    rawAffix: "` +(64-90)` Dexterity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Intelligence",
    valueRanges: [],
    rawAffix: "` +(64-90)` Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Strength",
    valueRanges: [],
    rawAffix: "` +(64-90)` Strength",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +2 Cold Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Cold Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +2 Erosion Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Erosion Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +2 Fire Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Fire Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +2 Lightning Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Lightning Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +2 Physical Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Physical Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template:
      "Reaps  (0.19-0.24) s of Damage Over Time when dealing Damage Over Time. The effect has a  1 s cooldown against the same target",
    valueRanges: [],
    rawAffix:
      "Reaps ` (0.19-0.24)` s of Damage Over Time when dealing Damage Over Time. The effect has a ` 1` s cooldown against the same target",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Damage Over Time",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Damage Over Time",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(150-188) Affliction inflicted per second",
    valueRanges: [],
    rawAffix: "` +(150-188)` Affliction inflicted per second",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(181-234) Max Mana",
    valueRanges: [],
    rawAffix: "` +(181-234)` Max Mana",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(331-429) Max Life",
    valueRanges: [],
    rawAffix: "` +(331-429)` Max Life",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(526-683) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(526-683)` Max Energy Shield",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template:
      "Reaps  (0.13-0.18) s of Damage Over Time when dealing Damage Over Time. The effect has a  1 s cooldown against the same target",
    valueRanges: [],
    rawAffix:
      "Reaps ` (0.13-0.18)` s of Damage Over Time when dealing Damage Over Time. The effect has a ` 1` s cooldown against the same target",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(120-144) Affliction inflicted per second",
    valueRanges: [],
    rawAffix: "` +(120-144)` Affliction inflicted per second",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(127-180) Max Mana",
    valueRanges: [],
    rawAffix: "` +(127-180)` Max Mana",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(232-330) Max Life",
    valueRanges: [],
    rawAffix: "` +(232-330)` Max Life",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(369-525) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(369-525)` Max Energy Shield",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Damage Over Time",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Damage Over Time",
  },
] as const satisfies readonly BaseGearAffix[];

export type ScepterPrefixAffix = (typeof SCEPTER_PREFIX_AFFIXES)[number];
