import { BaseGearAffix } from "./types";

export const SCEPTER_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(126-163)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(126-163)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(48-60)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(48-60)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(54-69)% additional damage against Frozen enemies",
    valueRanges: [],
    rawAffix: "` +(54-69)`% additional damage against Frozen enemies",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(55-65)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(55-65)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Terra Quantity  +1 \n+5% additional damage",
    valueRanges: [],
    rawAffix: "Max Terra Quantity ` +1` <> ` +5`% additional damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(35-45)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(35-45)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(38-53)% additional damage against Frozen enemies",
    valueRanges: [],
    rawAffix: "` +(38-53)`% additional damage against Frozen enemies",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(40-50)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(40-50)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(89-125)% Reaping Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(89-125)`% Reaping Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Terra Quantity  +1 \n+1% additional damage",
    valueRanges: [],
    rawAffix: "Max Terra Quantity ` +1` <> ` +1`% additional damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(25-31)% Wilt Duration",
    valueRanges: [],
    rawAffix: "` +(25-31)`% Wilt Duration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(25-31)% Ignite Duration",
    valueRanges: [],
    rawAffix: "` +(25-31)`% Ignite Duration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(25-31)% Trauma Duration",
    valueRanges: [],
    rawAffix: "` +(25-31)`% Trauma Duration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(37-47)% Cast Speed\n+(37-47)% Minion Cast Speed",
    valueRanges: [],
    rawAffix: "` +(37-47)`% Cast Speed<> ` +(37-47)`% Minion Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(60-70)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(60-70)`% Focus Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(76-98)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(76-98)`% Reaping Duration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Gains  40% of the skill's damage as Base Wilt Damage",
    valueRanges: [],
    rawAffix: "Gains ` 40`% of the skill's damage as Base Wilt Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Gains  50% of the skill's damage as Base Ignite Damage",
    valueRanges: [],
    rawAffix: "Gains ` 50`% of the skill's damage as Base Ignite Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Gains  81% of the skill's damage as Base Trauma Damage",
    valueRanges: [],
    rawAffix: "Gains ` 81`% of the skill's damage as Base Trauma Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(18-24)% Wilt Duration",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Wilt Duration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(18-24)% Ignite Duration",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Ignite Duration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(18-24)% Trauma Duration",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Trauma Duration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(26-36)% Cast Speed\n+(26-36)% Minion Cast Speed",
    valueRanges: [],
    rawAffix: "` +(26-36)`% Cast Speed<> ` +(26-36)`% Minion Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(45-54)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(45-54)`% Focus Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(54-75)% Reaping Duration",
    valueRanges: [],
    rawAffix: "` +(54-75)`% Reaping Duration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Gains  35% of the skill's damage as Base Wilt Damage",
    valueRanges: [],
    rawAffix: "Gains ` 35`% of the skill's damage as Base Wilt Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Gains  42% of the skill's damage as Base Ignite Damage",
    valueRanges: [],
    rawAffix: "Gains ` 42`% of the skill's damage as Base Ignite Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Gains  70% of the skill's damage as Base Trauma Damage",
    valueRanges: [],
    rawAffix: "Gains ` 70`% of the skill's damage as Base Trauma Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Erosion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-31)% Energy Shield Charge Speed",
    valueRanges: [],
    rawAffix: "` +(25-31)`% Energy Shield Charge Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(76-98)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(76-98)`% Affliction Effect",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(18-24)% Energy Shield Charge Speed",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Energy Shield Charge Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(54-75)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(54-75)`% Affliction Effect",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Erosion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(78-108)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(78-108)`% Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(78-108)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(78-108)`% Physical Damage",
  },
] as const satisfies readonly BaseGearAffix[];

export type ScepterSuffixAffix = (typeof SCEPTER_SUFFIX_AFFIXES)[number];
