import { BaseGearAffix } from "./types";

export const SCEPTER_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Scepter",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type ScepterBaseStatsAffix = (typeof SCEPTER_BASE_STATS_AFFIXES)[number];
