import { BaseGearAffix } from "./types";

export const SHIELD_INT_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(26-33)% additional Defense gained from Shield",
    valueRanges: [],
    rawAffix: "` +(26-33)`% additional Defense gained from Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(48-60)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(48-60)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(55-65)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(55-65)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(9-10)% Max Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(9-10)`% Max Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +2% Cast Speed and Skill Area for every  5% of Spell Block",
    valueRanges: [],
    rawAffix: "` +2`% Cast Speed and Skill Area for every ` 5`% of Spell Block",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Sentry Quantity  +1 \n+5% additional damage",
    valueRanges: [],
    rawAffix: "Max Sentry Quantity ` +1` <> ` +5`% additional damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(19-25)% additional Defense gained from Shield",
    valueRanges: [],
    rawAffix: "` +(19-25)`% additional Defense gained from Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(35-45)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(35-45)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(40-50)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(40-50)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(7-8)% Max Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(7-8)`% Max Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +1% Cast Speed and Skill Area for every  3% of Spell Block",
    valueRanges: [],
    rawAffix: "` +1`% Cast Speed and Skill Area for every ` 3`% of Spell Block",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Sentry Quantity  +1 ",
    valueRanges: [],
    rawAffix: "Max Sentry Quantity ` +1` ",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(165-234)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(165-234)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(34-47)% Attack and Cast Speed\n+(34-47)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(34-47)`% Attack and Cast Speed<> ` +(34-47)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(49-72)% Warcry Effect",
    valueRanges: [],
    rawAffix: "` +(49-72)`% Warcry Effect",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(60-70)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(60-70)`% Focus Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(83-117)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(83-117)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117)% Mana Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(91-117)`% Mana Regeneration Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +2 Max Warcry Skill Charges",
    valueRanges: [],
    rawAffix: "` +2` Max Warcry Skill Charges",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(127-180)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(26-36)% Attack and Cast Speed\n+(26-36)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(26-36)`% Attack and Cast Speed<> ` +(26-36)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(37-48)% Warcry Effect",
    valueRanges: [],
    rawAffix: "` +(37-48)`% Warcry Effect",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(45-54)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(45-54)`% Focus Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(64-90)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90)% Mana Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(64-90)`% Mana Regeneration Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +1 Max Warcry Skill Charges",
    valueRanges: [],
    rawAffix: "` +1` Max Warcry Skill Charges",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(15-18)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(15-18)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-31)% Energy Shield Charge Speed",
    valueRanges: [],
    rawAffix: "` +(25-31)`% Energy Shield Charge Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(41-45)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(41-45)`% Cold Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(41-45)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(41-45)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(41-45)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(41-45)`% Fire Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(41-45)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(41-45)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "Restores  (5-6)% Energy Shield on Block. Interval: 0.3s",
    valueRanges: [],
    rawAffix: "Restores ` (5-6)`% Energy Shield on Block. Interval: 0.3s",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(10-14)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(10-14)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(18-24)% Energy Shield Charge Speed",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Energy Shield Charge Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(29-40)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(29-40)`% Cold Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(29-40)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(29-40)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(29-40)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(29-40)`% Fire Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(29-40)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(29-40)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "Restores  4% Energy Shield on Block. Interval: 0.3s",
    valueRanges: [],
    rawAffix: "Restores ` 4`% Energy Shield on Block. Interval: 0.3s",
  },
] as const satisfies readonly BaseGearAffix[];

export type ShieldIntSuffixAffix = (typeof SHIELD_INT_SUFFIX_AFFIXES)[number];
