import { BaseGearAffix } from "./types";

export const SHIELD_DEX_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(26-33)% Armor DMG Mitigation Penetration\n+(26-33)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(26-33)`% Armor DMG Mitigation Penetration<> ` +(26-33)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(29-39)% Elemental and Erosion Resistance Penetration\nMinion Damage penetrates  (29-39)% Elemental Resistance",
    valueRanges: [],
    rawAffix:
      "` +(29-39)`% Elemental and Erosion Resistance Penetration<> Minion Damage penetrates ` (29-39)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(3-4) Active Skill Level",
    valueRanges: [],
    rawAffix: "` +(3-4)` Active Skill Level",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(19-25)% Armor DMG Mitigation Penetration\n+(19-25)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(19-25)`% Armor DMG Mitigation Penetration<> ` +(19-25)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(22-30)% Elemental and Erosion Resistance Penetration\nMinion Damage penetrates  (22-30)% Elemental Resistance",
    valueRanges: [],
    rawAffix:
      "` +(22-30)`% Elemental and Erosion Resistance Penetration<> Minion Damage penetrates ` (22-30)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +3 Active Skill Level",
    valueRanges: [],
    rawAffix: "` +3` Active Skill Level",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(16-20)% Block Ratio",
    valueRanges: [],
    rawAffix: "` +(16-20)`% Block Ratio",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(25-31)% Max Life",
    valueRanges: [],
    rawAffix: "` +(25-31)`% Max Life",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Dexterity",
    valueRanges: [],
    rawAffix: "` +(91-117)` Dexterity",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Intelligence",
    valueRanges: [],
    rawAffix: "` +(91-117)` Intelligence",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Strength",
    valueRanges: [],
    rawAffix: "` +(91-117)` Strength",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(12-15)% Block Ratio",
    valueRanges: [],
    rawAffix: "` +(12-15)`% Block Ratio",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(18-24)% Max Life",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Max Life",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Dexterity",
    valueRanges: [],
    rawAffix: "` +(64-90)` Dexterity",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Intelligence",
    valueRanges: [],
    rawAffix: "` +(64-90)` Intelligence",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Strength",
    valueRanges: [],
    rawAffix: "` +(64-90)` Strength",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " (-15--13)% additional Physical Damage taken",
    valueRanges: [],
    rawAffix: "` (-15--13)`% additional Physical Damage taken",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% damage\n+(109-140)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% damage<> ` +(109-140)`% Minion Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(20-25)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(20-25)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(331-429) Max Life",
    valueRanges: [],
    rawAffix: "` +(331-429)` Max Life",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(4321-5616) gear Evasion",
    valueRanges: [],
    rawAffix: "` +(4321-5616)` gear Evasion",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " (-12--10)% additional Physical Damage taken",
    valueRanges: [],
    rawAffix: "` (-12--10)`% additional Physical Damage taken",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(14-19)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(14-19)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(232-330) Max Life",
    valueRanges: [],
    rawAffix: "` +(232-330)` Max Life",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(3025-4320) gear Evasion",
    valueRanges: [],
    rawAffix: "` +(3025-4320)` gear Evasion",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% damage\n+(77-108)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% damage<> ` +(77-108)`% Minion Damage",
  },
] as const satisfies readonly BaseGearAffix[];

export type ShieldDexPrefixAffix = (typeof SHIELD_DEX_PREFIX_AFFIXES)[number];
