import { BaseGearAffix } from "./types";

export const SHIELD_INT_BASE_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: " +(4-5)% Max Elemental and Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(4-5)`% Max Elemental and Erosion Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Converts  (12-15)% of Physical Damage taken to Cold Damage",
    valueRanges: [],
    rawAffix: "Converts ` (12-15)`% of Physical Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Converts  (27-35)% of Erosion Damage taken to Cold Damage",
    valueRanges: [],
    rawAffix: "Converts ` (27-35)`% of Erosion Damage taken to Cold Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(35-40) Dexterity",
    valueRanges: [],
    rawAffix: "` +(35-40)` Dexterity",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(35-40) Intelligence",
    valueRanges: [],
    rawAffix: "` +(35-40)` Intelligence",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(35-40) Strength",
    valueRanges: [],
    rawAffix: "` +(35-40)` Strength",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% additional damage",
    valueRanges: [],
    rawAffix: "` +(6-8)`% additional damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Elemental Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Erosion Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Physical Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(4-6)% Energy Shield Charge Speed",
    valueRanges: [],
    rawAffix: "` +(4-6)`% Energy Shield Charge Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Cold Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Fire Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(5-10)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(5-10)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(8-10)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(8-10)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(87-117) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(87-117)` Max Energy Shield",
  },
] as const satisfies readonly BaseGearAffix[];

export type ShieldIntBaseAffixAffix =
  (typeof SHIELD_INT_BASE_AFFIX_AFFIXES)[number];
