import { BaseGearAffix } from "./types";

export const SHIELD_DEX_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(31-39)% additional Defense gained from Shield",
    valueRanges: [],
    rawAffix: "` +(31-39)`% additional Defense gained from Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(48-60)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(48-60)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(55-65)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(55-65)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(9-10)% Max Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(9-10)`% Max Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +1% Attack Speed and Movement Speed for every  6% of Attack or Spell Block",
    valueRanges: [],
    rawAffix:
      "` +1`% Attack Speed and Movement Speed for every ` 6`% of Attack or Spell Block",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Sentry Quantity  +1 \n+5% additional damage",
    valueRanges: [],
    rawAffix: "Max Sentry Quantity ` +1` <> ` +5`% additional damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(22-30)% additional Defense gained from Shield",
    valueRanges: [],
    rawAffix: "` +(22-30)`% additional Defense gained from Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(35-45)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(35-45)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(40-50)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(40-50)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(7-8)% Max Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(7-8)`% Max Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +1% Attack Speed and Movement Speed for every  (7-8)% of Attack or Spell Block",
    valueRanges: [],
    rawAffix:
      "` +1`% Attack Speed and Movement Speed for every ` (7-8)`% of Attack or Spell Block",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Sentry Quantity  +1 ",
    valueRanges: [],
    rawAffix: "Max Sentry Quantity ` +1` ",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(165-234)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(165-234)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(34-47)% Attack and Cast Speed\n+(34-47)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(34-47)`% Attack and Cast Speed<> ` +(34-47)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(49-72)% Warcry Effect",
    valueRanges: [],
    rawAffix: "` +(49-72)`% Warcry Effect",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(60-70)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(60-70)`% Focus Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(83-117)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(83-117)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +2 Max Warcry Skill Charges",
    valueRanges: [],
    rawAffix: "` +2` Max Warcry Skill Charges",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(127-180)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(26-36)% Attack and Cast Speed\n+(26-36)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(26-36)`% Attack and Cast Speed<> ` +(26-36)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(37-48)% Warcry Effect",
    valueRanges: [],
    rawAffix: "` +(37-48)`% Warcry Effect",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(45-54)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(45-54)`% Focus Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(64-90)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +1 Max Warcry Skill Charges",
    valueRanges: [],
    rawAffix: "` +1` Max Warcry Skill Charges",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(15-18)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(15-18)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(41-45)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(41-45)`% Cold Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(41-45)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(41-45)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(41-45)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(41-45)`% Fire Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(41-45)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(41-45)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "Regenerates  (177-234) Life per second",
    valueRanges: [],
    rawAffix: "Regenerates ` (177-234)` Life per second",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: "Restores  (5-6)% Life on Block. Interval: 0.3s",
    valueRanges: [],
    rawAffix: "Restores ` (5-6)`% Life on Block. Interval: 0.3s",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(10-14)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(10-14)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(29-40)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(29-40)`% Cold Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(29-40)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(29-40)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(29-40)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(29-40)`% Fire Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(29-40)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(29-40)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "Regenerates  (136-180) Life per second",
    valueRanges: [],
    rawAffix: "Regenerates ` (136-180)` Life per second",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (DEX)",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: "Restores  4% Life on Block. Interval: 0.3s",
    valueRanges: [],
    rawAffix: "Restores ` 4`% Life on Block. Interval: 0.3s",
  },
] as const satisfies readonly BaseGearAffix[];

export type ShieldDexSuffixAffix = (typeof SHIELD_DEX_SUFFIX_AFFIXES)[number];
