import { BaseGearAffix } from "./types";

export const SHIELD_INT_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(26-33)% Armor DMG Mitigation Penetration\n+(26-33)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(26-33)`% Armor DMG Mitigation Penetration<> ` +(26-33)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(29-39)% Elemental and Erosion Resistance Penetration\nMinion Damage penetrates  (29-39)% Elemental Resistance",
    valueRanges: [],
    rawAffix:
      "` +(29-39)`% Elemental and Erosion Resistance Penetration<> Minion Damage penetrates ` (29-39)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(3-4) Active Skill Level",
    valueRanges: [],
    rawAffix: "` +(3-4)` Active Skill Level",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(19-25)% Armor DMG Mitigation Penetration\n+(19-25)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(19-25)`% Armor DMG Mitigation Penetration<> ` +(19-25)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(22-30)% Elemental and Erosion Resistance Penetration\nMinion Damage penetrates  (22-30)% Elemental Resistance",
    valueRanges: [],
    rawAffix:
      "` +(22-30)`% Elemental and Erosion Resistance Penetration<> Minion Damage penetrates ` (22-30)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +3 Active Skill Level",
    valueRanges: [],
    rawAffix: "` +3` Active Skill Level",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(16-20)% Block Ratio",
    valueRanges: [],
    rawAffix: "` +(16-20)`% Block Ratio",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(25-31)% Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(25-31)`% Max Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Dexterity",
    valueRanges: [],
    rawAffix: "` +(91-117)` Dexterity",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Intelligence",
    valueRanges: [],
    rawAffix: "` +(91-117)` Intelligence",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Strength",
    valueRanges: [],
    rawAffix: "` +(91-117)` Strength",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(12-15)% Block Ratio",
    valueRanges: [],
    rawAffix: "` +(12-15)`% Block Ratio",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(18-24)% Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Max Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Dexterity",
    valueRanges: [],
    rawAffix: "` +(64-90)` Dexterity",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Intelligence",
    valueRanges: [],
    rawAffix: "` +(64-90)` Intelligence",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Strength",
    valueRanges: [],
    rawAffix: "` +(64-90)` Strength",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " (-15--13)% additional Physical Damage taken",
    valueRanges: [],
    rawAffix: "` (-15--13)`% additional Physical Damage taken",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% damage\n+(109-140)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% damage<> ` +(109-140)`% Minion Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(181-234) Max Mana",
    valueRanges: [],
    rawAffix: "` +(181-234)` Max Mana",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(20-25)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(20-25)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(311-442) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(311-442)` Max Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " (-12--10)% additional Physical Damage taken",
    valueRanges: [],
    rawAffix: "` (-12--10)`% additional Physical Damage taken",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(127-180) Max Mana",
    valueRanges: [],
    rawAffix: "` +(127-180)` Max Mana",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(14-19)% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(14-19)`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(239-340) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(239-340)` Max Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% damage\n+(77-108)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% damage<> ` +(77-108)`% Minion Damage",
  },
] as const satisfies readonly BaseGearAffix[];

export type ShieldIntPrefixAffix = (typeof SHIELD_INT_PREFIX_AFFIXES)[number];
