import { BaseGearAffix } from "./types";

export const SHIELD_STR_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1122 Gear Armor",
    valueRanges: [],
    rawAffix: "` +1122` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1346 Gear Armor",
    valueRanges: [],
    rawAffix: "` +1346` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1615 Gear Armor",
    valueRanges: [],
    rawAffix: "` +1615` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +168 Gear Armor",
    valueRanges: [],
    rawAffix: "` +168` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1777 Gear Armor",
    valueRanges: [],
    rawAffix: "` +1777` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +1920 Gear Armor",
    valueRanges: [],
    rawAffix: "` +1920` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +235 Gear Armor",
    valueRanges: [],
    rawAffix: "` +235` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +329 Gear Armor",
    valueRanges: [],
    rawAffix: "` +329` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +461 Gear Armor",
    valueRanges: [],
    rawAffix: "` +461` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +599 Gear Armor",
    valueRanges: [],
    rawAffix: "` +599` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +779 Gear Armor",
    valueRanges: [],
    rawAffix: "` +779` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    template: " +935 Gear Armor",
    valueRanges: [],
    rawAffix: "` +935` Gear Armor",
  },
] as const satisfies readonly BaseGearAffix[];

export type ShieldStrBaseStatsAffix =
  (typeof SHIELD_STR_BASE_STATS_AFFIXES)[number];
