import { BaseGearAffix } from "./types";

export const SHIELD_INT_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+103gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+120gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+13gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+146gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+18gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+26gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+35gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+43gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+56gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+69gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+86gear Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (INT)",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "+9gear Energy Shield",
  },
] as const satisfies readonly BaseGearAffix[];

export type ShieldIntBaseStatsAffix =
  (typeof SHIELD_INT_BASE_STATS_AFFIXES)[number];
