import { BaseGearAffix } from "./types";

export const SHIELD_STR_TOWER_SEQUENCE_AFFIXES = [
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      " +15% Armor Effective Rate for Non-Physical Damage\n+2400 Gear Armor",
    valueRanges: [],
    rawAffix:
      "` +15`% Armor Effective Rate for Non-Physical Damage<> ` +2400` Gear Armor",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: " +8% Block Ratio Upper limit",
    valueRanges: [],
    rawAffix: "` +8`% Block Ratio Upper limit",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "All Passive Skill slots are supported by Lv.  30 Precise: Restrain",
    valueRanges: [],
    rawAffix:
      "All Passive Skill slots are supported by Lv. ` 30` Precise: Restrain",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Converts  25% of Physical Damage taken to random Elemental Damage\n-25% Defense",
    valueRanges: [],
    rawAffix:
      "Converts ` 25`% of Physical Damage taken to random Elemental Damage<> ` -25`% Defense",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Energy Shield starts to Charge when Blocking\n+40% Energy Shield Charge Speed",
    valueRanges: [],
    rawAffix:
      "Energy Shield starts to Charge when Blocking<> ` +40`% Energy Shield Charge Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Immune to crowd control effects",
    valueRanges: [],
    rawAffix: "Immune to crowd control effects",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Spell Damage will not further reduce Evasion by default\n+1680 gear Evasion",
    valueRanges: [],
    rawAffix:
      "Spell Damage will not further reduce Evasion by default<> ` +1680` gear Evasion",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +10% Attack and Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +10`% Attack and Spell Block Chance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +12% Movement Speed",
    valueRanges: [],
    rawAffix: "` +12`% Movement Speed",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +15% Max Life and Max Mana",
    valueRanges: [],
    rawAffix: "` +15`% Max Life and Max Mana",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +40% Defense from Shield",
    valueRanges: [],
    rawAffix: "` +40`% Defense from Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +40% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +40`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +8`% Elemental Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% all stats",
    valueRanges: [],
    rawAffix: "` +8`% all stats",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +80% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +80`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "Restores  3% Energy Shield on Block. Interval: 0.3s",
    valueRanges: [],
    rawAffix: "Restores ` 3`% Energy Shield on Block. Interval: 0.3s",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: "Restores  3% Life on Block. Interval: 0.3s",
    valueRanges: [],
    rawAffix: "Restores ` 3`% Life on Block. Interval: 0.3s",
  },
] as const satisfies readonly BaseGearAffix[];

export type ShieldStrTowerSequenceAffix =
  (typeof SHIELD_STR_TOWER_SEQUENCE_AFFIXES)[number];
