import { BaseGearAffix } from "./types";

export const SHIELD_STR_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(1-2)% Max Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(1-2)`% Max Cold Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(1-2)% Max Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(1-2)`% Max Fire Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(1-2)% Max Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(1-2)`% Max Lightning Resistance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(12-15)% Spell Block Chance",
    valueRanges: [],
    rawAffix: "` +(12-15)`% Spell Block Chance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(3-5)% Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(3-5)`% Max Energy Shield",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(3-5)% Max Life",
    valueRanges: [],
    rawAffix: "` +(3-5)`% Max Life",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(5-8)% Block Ratio",
    valueRanges: [],
    rawAffix: "` +(5-8)`% Block Ratio",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(8-12)% Attack Block Chance",
    valueRanges: [],
    rawAffix: "` +(8-12)`% Attack Block Chance",
  },
  {
    equipmentSlot: "Shield",
    equipmentType: "Shield (STR)",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Has a  (5-10)% chance to avoid Blocked damage",
    valueRanges: [],
    rawAffix: "Has a ` (5-10)`% chance to avoid Blocked damage",
  },
] as const satisfies readonly BaseGearAffix[];

export type ShieldStrCorrosionBaseAffix =
  (typeof SHIELD_STR_CORROSION_BASE_AFFIXES)[number];
