import { BaseGearAffix } from "./types";

export const SPIRIT_RING_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(18-22)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix: "` +(18-22)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(21-26)% Elemental and Erosion Resistance Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(21-26)`% Elemental and Erosion Resistance Penetration for Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Agility Blessing Stacks  +1 \n+5% additional Minion Damage",
    valueRanges: [],
    rawAffix:
      "Max Agility Blessing Stacks ` +1` <> ` +5`% additional Minion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Focus Blessing Stacks  +1 \n+5% additional Minion Damage",
    valueRanges: [],
    rawAffix:
      "Max Focus Blessing Stacks ` +1` <> ` +5`% additional Minion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Tenacity Blessing Stacks  +1 \n+5% additional Minion Damage",
    valueRanges: [],
    rawAffix:
      "Max Tenacity Blessing Stacks ` +1` <> ` +5`% additional Minion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(13-17)% Armor DMG Mitigation Penetration for Minions",
    valueRanges: [],
    rawAffix: "` +(13-17)`% Armor DMG Mitigation Penetration for Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(15-20)% Elemental and Erosion Resistance Penetration for Minions",
    valueRanges: [],
    rawAffix:
      "` +(15-20)`% Elemental and Erosion Resistance Penetration for Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Agility Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Agility Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Focus Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Tenacity Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Tenacity Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Dexterity",
    valueRanges: [],
    rawAffix: "` +(61-78)` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Intelligence",
    valueRanges: [],
    rawAffix: "` +(61-78)` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78) Strength",
    valueRanges: [],
    rawAffix: "` +(61-78)` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (54-56) -  (71-76) Fire Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (54-56)` - ` (71-76)` Fire Damage to Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (55-57) -  (73-75) Cold Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (55-57)` - ` (73-75)` Cold Damage to Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (58-60) -  (71-73) Erosion Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (58-60)` - ` (71-73)` Erosion Damage to Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (58-60) -  (71-73) Physical Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (58-60)` - ` (71-73)` Physical Damage to Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: "Adds  (6-8) -  (123-125) Lightning Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (6-8)` - ` (123-125)` Lightning Damage to Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Dexterity",
    valueRanges: [],
    rawAffix: "` +(43-60)` Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Intelligence",
    valueRanges: [],
    rawAffix: "` +(43-60)` Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(43-60) Strength",
    valueRanges: [],
    rawAffix: "` +(43-60)` Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (4-6) -  (94-96) Lightning Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (4-6)` - ` (94-96)` Lightning Damage to Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (42-44) -  (54-59) Fire Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (42-44)` - ` (54-59)` Fire Damage to Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (42-44) -  (56-58) Cold Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (42-44)` - ` (56-58)` Cold Damage to Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (44-46) -  (54-56) Erosion Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (44-46)` - ` (54-56)` Erosion Damage to Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: "Adds  (44-46) -  (54-56) Physical Damage to Minions",
    valueRanges: [],
    rawAffix: "Adds ` (44-46)` - ` (54-56)` Physical Damage to Minions",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156) Max Mana",
    valueRanges: [],
    rawAffix: "` +(121-156)` Max Mana",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(17-24)% Life Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(17-24)`% Life Regeneration Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(221-286) Max Life",
    valueRanges: [],
    rawAffix: "` +(221-286)` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-31)% Minion Life Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(25-31)`% Minion Life Regeneration Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(319-455) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(319-455)` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(37-47)% Armor",
    valueRanges: [],
    rawAffix: "` +(37-47)`% Armor",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(37-47)% Evasion",
    valueRanges: [],
    rawAffix: "` +(37-47)`% Evasion",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(73-94)`% Minion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(11-16)% Life Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(11-16)`% Life Regeneration Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(155-220) Max Life",
    valueRanges: [],
    rawAffix: "` +(155-220)` Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(18-24)% Minion Life Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Minion Life Regeneration Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(245-350) Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(245-350)` Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(27-36)% Armor",
    valueRanges: [],
    rawAffix: "` +(27-36)`% Armor",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(27-36)% Evasion",
    valueRanges: [],
    rawAffix: "` +(27-36)`% Evasion",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(52-72)% Minion Damage",
    valueRanges: [],
    rawAffix: "` +(52-72)`% Minion Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(85-120) Max Mana",
    valueRanges: [],
    rawAffix: "` +(85-120)` Max Mana",
  },
] as const satisfies readonly BaseGearAffix[];

export type SpiritRingPrefixAffix = (typeof SPIRIT_RING_PREFIX_AFFIXES)[number];
