import { BaseGearAffix } from "./types";

export const SPIRIT_RING_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "+  (11-13) Command per second",
    valueRanges: [],
    rawAffix: "+ ` (11-13)` Command per second",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(126-163) Minion Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(126-163)` Minion Critical Strike Rating",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(13-16)% Elemental Resistance\n+(13-16)% Erosion Resistance",
    valueRanges: [],
    rawAffix:
      "` +(13-16)`% Elemental Resistance<> ` +(13-16)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(27-34)% chance for Minions to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(27-34)`% chance for Minions to deal Double Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(81-104) initial Growth for Spirit Magi",
    valueRanges: [],
    rawAffix: "` +(81-104)` initial Growth for Spirit Magi",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "+  (8-10) Command per second",
    valueRanges: [],
    rawAffix: "+ ` (8-10)` Command per second",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(19-26)% chance for Minions to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(19-26)`% chance for Minions to deal Double Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(57-80) initial Growth for Spirit Magi",
    valueRanges: [],
    rawAffix: "` +(57-80)` initial Growth for Spirit Magi",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(89-125) Minion Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(89-125)` Minion Critical Strike Rating",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(9-12)% Elemental Resistance\n+(9-12)% Erosion Resistance",
    valueRanges: [],
    rawAffix:
      "` +(9-12)`% Elemental Resistance<> ` +(9-12)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(25-31)% Attack and Cast Speed\n+(25-31)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(25-31)`% Attack and Cast Speed<> ` +(25-31)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(56-72)% Minion Max Life",
    valueRanges: [],
    rawAffix: "` +(56-72)`% Minion Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(61-78)% Minion Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Minion Critical Strike Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      "While Reconjuring , Spirit Magi regenerate  (16-20)% Life per second",
    valueRanges: [],
    rawAffix:
      "While Reconjuring , Spirit Magi regenerate ` (16-20)`% Life per second",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(18-24)% Attack and Cast Speed\n+(18-24)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(18-24)`% Attack and Cast Speed<> ` +(18-24)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(40-55)% Minion Max Life",
    valueRanges: [],
    rawAffix: "` +(40-55)`% Minion Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(44-60)% Minion Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(44-60)`% Minion Critical Strike Damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      "While Reconjuring , Spirit Magi regenerate  (12-15)% Life per second",
    valueRanges: [],
    rawAffix:
      "While Reconjuring , Spirit Magi regenerate ` (12-15)`% Life per second",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(121-156)% Minion Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(121-156)`% Minion Critical Strike Rating",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(25-35)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(25-35)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Cold Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Erosion Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Fire Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(19-27)% Lightning Resistance",
    valueRanges: [],
    rawAffix: "` +(19-27)`% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(87-120)% Minion Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(87-120)`% Minion Critical Strike Rating",
  },
] as const satisfies readonly BaseGearAffix[];

export type SpiritRingSuffixAffix = (typeof SPIRIT_RING_SUFFIX_AFFIXES)[number];
