import { BaseGearAffix } from "./types";

export const SPIRIT_RING_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-25)% Max Energy Shield",
    valueRanges: [],
    rawAffix: "` +(15-25)`% Max Energy Shield",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(15-25)% Max Life",
    valueRanges: [],
    rawAffix: "` +(15-25)`% Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(5-6)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "` +(5-6)`% Elemental Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(50-70)% damage",
    valueRanges: [],
    rawAffix: "` +(50-70)`% damage",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(6-8)% Attack Speed",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Attack Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(6-8)% Cast Speed",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Cast Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(8-10)% Dexterity",
    valueRanges: [],
    rawAffix: "` +(8-10)`% Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(8-10)% Intelligence",
    valueRanges: [],
    rawAffix: "` +(8-10)`% Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(8-10)% Strength",
    valueRanges: [],
    rawAffix: "` +(8-10)`% Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +5% Movement Speed",
    valueRanges: [],
    rawAffix: "` +5`% Movement Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +5% XP earned",
    valueRanges: [],
    rawAffix: "` +5`% XP earned",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Immune to Trauma\nImmune to Wilt",
    valueRanges: [],
    rawAffix: "Immune to Trauma<> Immune to Wilt",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Immune to curse",
    valueRanges: [],
    rawAffix: "Immune to curse",
  },
] as const satisfies readonly BaseGearAffix[];

export type SpiritRingCorrosionBaseAffix =
  (typeof SPIRIT_RING_CORROSION_BASE_AFFIXES)[number];
