import { BaseGearAffix } from "./types";

export const SPIRIT_RING_SWEET_DREAM_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    craftableAffix: "Max Focus Blessing Stacks +1",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    craftableAffix: "Max Tenacity Blessing Stacks +1",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    craftableAffix:
      "Triggers Lv. 20Frost Touch Curse upon inflicting damage. Cooldown: 0.2 s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    craftableAffix:
      "Triggers Lv. 20Blind Curse upon inflicting damage. Cooldown: 0.2 s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    craftableAffix:
      "Triggers Lv. 20Timid Curse upon inflicting damage. Cooldown: 0.2 s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    craftableAffix:
      "Triggers Lv. 20Entangled Pain Curse upon inflicting damage. Cooldown: 0.2 s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    craftableAffix: "+ 3Command per second",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    craftableAffix: "+(11-15)% Movement Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    craftableAffix: "+32initial Growth for Spirit Magi",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    craftableAffix:
      "When Minions deal damage, inflicts Cold Infiltration . Interval for each enemy: 2s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    craftableAffix:
      "When Minions deal damage, inflicts Fire Infiltration . Interval for each enemy: 2s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    craftableAffix:
      "When Minions deal damage, inflicts Lightning Infiltration . Interval for each enemy: 2s",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    craftableAffix: "+(15-20)Dexterity",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    craftableAffix: "+(15-20)Intelligence",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    craftableAffix: "+(15-20)Strength",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    craftableAffix: "+(5-10)% Cold Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    craftableAffix: "+(5-10)% Erosion Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    craftableAffix: "+(5-10)% Fire Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    craftableAffix: "+(5-10)% Lightning Resistance",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    craftableAffix: "+(54-74)Max Life",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    craftableAffix:
      "+(6-8)% Minion Movement Speed, Attack Speed, and Cast Speed",
  },
  {
    equipmentSlot: "Trinket",
    equipmentType: "Spirit Ring",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    craftableAffix: "+(87-117)Max Energy Shield",
  },
] as const satisfies readonly BaseGearAffix[];

export type SpiritRingSweetDreamAffixAffix =
  (typeof SPIRIT_RING_SWEET_DREAM_AFFIX_AFFIXES)[number];
