import { BaseGearAffix } from "./types";

export const TIN_STAFF_PREFIX_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(51-65)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(61-78)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(61-78)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +4 Jumps\n+(25-30)% additional damage",
    valueRanges: [],
    rawAffix: "` +4` Jumps<> ` +(25-30)`% additional damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +7 Spell Skill Level",
    valueRanges: [],
    rawAffix: "` +7` Spell Skill Level",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Terra Charge Stacks  +(5-6) ",
    valueRanges: [],
    rawAffix: "Max Terra Charge Stacks ` +(5-6)` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Channeled Stacks  +5 ",
    valueRanges: [],
    rawAffix: "Max Channeled Stacks ` +5` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Min Channeled Stacks  +5 ",
    valueRanges: [],
    rawAffix: "Min Channeled Stacks ` +5` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(36-50)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(44-60)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(44-60)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +4 Jumps\n+(18-20)% additional damage",
    valueRanges: [],
    rawAffix: "` +4` Jumps<> ` +(18-20)`% additional damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +6 Spell Skill Level",
    valueRanges: [],
    rawAffix: "` +6` Spell Skill Level",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Terra Charge Stacks  +(3-4) ",
    valueRanges: [],
    rawAffix: "Max Terra Charge Stacks ` +(3-4)` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Channeled Stacks  +4 ",
    valueRanges: [],
    rawAffix: "Max Channeled Stacks ` +4` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Min Channeled Stacks  +4 ",
    valueRanges: [],
    rawAffix: "Min Channeled Stacks ` +4` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234) Dexterity",
    valueRanges: [],
    rawAffix: "` +(181-234)` Dexterity",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234) Intelligence",
    valueRanges: [],
    rawAffix: "` +(181-234)` Intelligence",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234) Strength",
    valueRanges: [],
    rawAffix: "` +(181-234)` Strength",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(4-5) Main Skill Level",
    valueRanges: [],
    rawAffix: "` +(4-5)` Main Skill Level",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180) Dexterity",
    valueRanges: [],
    rawAffix: "` +(127-180)` Dexterity",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180) Intelligence",
    valueRanges: [],
    rawAffix: "` +(127-180)` Intelligence",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180) Strength",
    valueRanges: [],
    rawAffix: "` +(127-180)` Strength",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +4 Main Skill Level",
    valueRanges: [],
    rawAffix: "` +4` Main Skill Level",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(217-281)% Spell Damage",
    valueRanges: [],
    rawAffix: "` +(217-281)`% Spell Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(361-468) Max Mana",
    valueRanges: [],
    rawAffix: "` +(361-468)` Max Mana",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (166-168) -  (215-226) Fire Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (166-168)` - ` (215-226)` Fire Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (168-170) -  (222-224) Cold Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (168-170)` - ` (222-224)` Cold Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (179-181) -  (211-213) Erosion Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (179-181)` - ` (211-213)` Erosion Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (179-181) -  (211-213) Physical Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (179-181)` - ` (211-213)` Physical Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (19-21) -  (371-373) Lightning Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (19-21)` - ` (371-373)` Lightning Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(152-216)% Spell Damage",
    valueRanges: [],
    rawAffix: "` +(152-216)`% Spell Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(253-360) Max Mana",
    valueRanges: [],
    rawAffix: "` +(253-360)` Max Mana",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (127-129) -  (164-174) Fire Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (127-129)` - ` (164-174)` Fire Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (128-130) -  (170-172) Cold Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (128-130)` - ` (170-172)` Cold Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (137-139) -  (161-163) Erosion Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (137-139)` - ` (161-163)` Erosion Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (137-139) -  (161-163) Physical Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (137-139)` - ` (161-163)` Physical Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (14-16) -  (284-286) Lightning Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (14-16)` - ` (284-286)` Lightning Damage to Spells",
  },
] as const satisfies readonly BaseGearAffix[];

export type TinStaffPrefixAffix = (typeof TIN_STAFF_PREFIX_AFFIXES)[number];
