import { BaseGearAffix } from "./types";

export const TIN_STAFF_SWEET_DREAM_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Lucky Critical Strike\n(-50--80)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "Lucky Critical Strike<> ` (-50--80)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Enemies have a  (20-25)% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to  (15-25)% of their Max Life to enemies within a  5 m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a ` (20-25)`% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to ` (15-25)`% of their Max Life to enemies within a ` 5` m radius",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Agility Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Agility Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Focus Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Tenacity Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Tenacity Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(24-32)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(24-32)`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(5-7)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(5-7)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% additional damage when channeling",
    valueRanges: [],
    rawAffix: "` +(6-8)`% additional damage when channeling",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% additional Spell Damage",
    valueRanges: [],
    rawAffix: "` +(6-8)`% additional Spell Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "1",
    template: "Adds  (32-34) -  (40-42) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (32-34)` - ` (40-42)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Erosion Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Spell Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Spell Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: " +(6-8)% Cast Speed",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Cast Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (1-2) -  (28-32) Lightning Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (1-2)` - ` (28-32)` Lightning Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (10-13) -  (14-19) Cold Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (10-13)` - ` (14-19)` Cold Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (10-13) -  (14-19) Physical Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (10-13)` - ` (14-19)` Physical Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (11-13) -  (15-18) Erosion Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (11-13)` - ` (15-18)` Erosion Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Sweet Dream Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (9-14) -  (15-20) Fire Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (9-14)` - ` (15-20)` Fire Damage to Spells",
  },
] as const satisfies readonly BaseGearAffix[];

export type TinStaffSweetDreamAffixAffix =
  (typeof TIN_STAFF_SWEET_DREAM_AFFIX_AFFIXES)[number];
