import { BaseGearAffix } from "./types";

export const TIN_STAFF_BASE_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template:
      "Enemies have a  (20-25)% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to  (15-25)% of their Max Life to enemies within a  5 m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a ` (20-25)`% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to ` (15-25)`% of their Max Life to enemies within a ` 5` m radius",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Agility Blessing Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Agility Blessing Stacks ` +2` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Focus Blessing Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks ` +2` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Tenacity Blessing Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Tenacity Blessing Stacks ` +2` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(10-14)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(10-14)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(12-16)% additional damage when channeling",
    valueRanges: [],
    rawAffix: "` +(12-16)`% additional damage when channeling",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(12-16)% additional Spell Damage",
    valueRanges: [],
    rawAffix: "` +(12-16)`% additional Spell Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(12-16)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(12-16)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(12-16)% Cast Speed",
    valueRanges: [],
    rawAffix: "` +(12-16)`% Cast Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Erosion Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Spell Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Spell Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (1-3) -  (60-65) Lightning Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (1-3)` - ` (60-65)` Lightning Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (24-29) -  (34-39) Cold Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (24-29)` - ` (34-39)` Cold Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (24-29) -  (34-39) Fire Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (24-29)` - ` (34-39)` Fire Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (25-30) -  (33-38) Physical Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (25-30)` - ` (33-38)` Physical Damage to Spells",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (26-31) -  (32-37) Erosion Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (26-31)` - ` (32-37)` Erosion Damage to Spells",
  },
] as const satisfies readonly BaseGearAffix[];

export type TinStaffBaseAffixAffix =
  (typeof TIN_STAFF_BASE_AFFIX_AFFIXES)[number];
