import { BaseGearAffix } from "./types";

export const TIN_STAFF_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " (61-78)% additional damage applied to Life",
    valueRanges: [],
    rawAffix: "` (61-78)`% additional damage applied to Life",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(110-130)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(110-130)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(61-78)% additional damage when channeling",
    valueRanges: [],
    rawAffix: "` +(61-78)`% additional damage when channeling",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(96-120)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(96-120)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +4 Beams\n+(20-30)% additional damage",
    valueRanges: [],
    rawAffix: "` +4` Beams<> ` +(20-30)`% additional damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Terra Quantity  +2 \n+10% additional damage",
    valueRanges: [],
    rawAffix: "Max Terra Quantity ` +2` <> ` +10`% additional damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " (43-60)% additional damage applied to Life",
    valueRanges: [],
    rawAffix: "` (43-60)`% additional damage applied to Life",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(44-60)% additional damage when channeling",
    valueRanges: [],
    rawAffix: "` +(44-60)`% additional damage when channeling",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(70-90)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(70-90)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(80-100)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(80-100)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +4 Beams\n+(5-10)% additional damage",
    valueRanges: [],
    rawAffix: "` +4` Beams<> ` +(5-10)`% additional damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Terra Quantity  +2 \n+1% additional damage",
    valueRanges: [],
    rawAffix: "Max Terra Quantity ` +2` <> ` +1`% additional damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(120-140)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(120-140)`% Focus Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234)% Mana Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(181-234)`% Mana Regeneration Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234)% Spell Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(181-234)`% Spell Critical Strike Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(251-325) Spell Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(251-325)` Spell Critical Strike Rating",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(361-468)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(361-468)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(88-125)% Max Mana",
    valueRanges: [],
    rawAffix: "` +(88-125)`% Max Mana",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180)% Mana Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(127-180)`% Mana Regeneration Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180)% Spell Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(127-180)`% Spell Critical Strike Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(176-250) Spell Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(176-250)` Spell Critical Strike Rating",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(253-360)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(253-360)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(68-96)% Max Mana",
    valueRanges: [],
    rawAffix: "` +(68-96)`% Max Mana",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(90-110)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(90-110)`% Focus Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(100-130)% Spell Burst Charge Speed",
    valueRanges: [],
    rawAffix: "` +(100-130)`% Spell Burst Charge Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(197-281)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(197-281)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(197-281)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(197-281)`% Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(217-281)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(217-281)`% Erosion Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(31-39)% Energy Shield Regain",
    valueRanges: [],
    rawAffix: "` +(31-39)`% Energy Shield Regain",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(31-39)% Life Regain",
    valueRanges: [],
    rawAffix: "` +(31-39)`% Life Regain",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(73-94)% Cast Speed\n+(73-94)% Minion Cast Speed",
    valueRanges: [],
    rawAffix: "` +(73-94)`% Cast Speed<> ` +(73-94)`% Minion Cast Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(152-216)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(152-216)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(152-216)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(152-216)`% Erosion Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(152-216)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(152-216)`% Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(22-30)% Energy Shield Regain",
    valueRanges: [],
    rawAffix: "` +(22-30)`% Energy Shield Regain",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(22-30)% Life Regain",
    valueRanges: [],
    rawAffix: "` +(22-30)`% Life Regain",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(51-72)% Cast Speed\n+(51-72)% Minion Cast Speed",
    valueRanges: [],
    rawAffix: "` +(51-72)`% Cast Speed<> ` +(51-72)`% Minion Cast Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(76-95)% Spell Burst Charge Speed",
    valueRanges: [],
    rawAffix: "` +(76-95)`% Spell Burst Charge Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type TinStaffSuffixAffix = (typeof TIN_STAFF_SUFFIX_AFFIXES)[number];
