import { BaseGearAffix } from "./types";

export const TIN_STAFF_CORROSION_BASE_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(1-2) Support Skill Level",
    valueRanges: [],
    rawAffix: "` +(1-2)` Support Skill Level",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(18-24)% Cast Speed",
    valueRanges: [],
    rawAffix: "` +(18-24)`% Cast Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(35-45)% Spell Damage",
    valueRanges: [],
    rawAffix: "` +(35-45)`% Spell Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(40-48)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(50-60)% Spell Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(50-60)`% Spell Critical Strike Rating",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(6-12)% chance to gain 1 stack of Focus Blessing on defeat",
    valueRanges: [],
    rawAffix: "` +(6-12)`% chance to gain 1 stack of Focus Blessing on defeat",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: " +(8-15)% Cooldown Recovery Speed",
    valueRanges: [],
    rawAffix: "` +(8-15)`% Cooldown Recovery Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Adds  (7-12)% of Elemental Damage as Erosion Damage",
    valueRanges: [],
    rawAffix: "Adds ` (7-12)`% of Elemental Damage as Erosion Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Corrosion Base",
    craftingPool: "",
    tier: "0",
    template: "Damage Penetrates  (8-12)% Elemental Resistance",
    valueRanges: [],
    rawAffix: "Damage Penetrates ` (8-12)`% Elemental Resistance",
  },
] as const satisfies readonly BaseGearAffix[];

export type TinStaffCorrosionBaseAffix =
  (typeof TIN_STAFF_CORROSION_BASE_AFFIXES)[number];
