import { BaseGearAffix } from "./types";

export const TIN_STAFF_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Tin Staff",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type TinStaffBaseStatsAffix =
  (typeof TIN_STAFF_BASE_STATS_AFFIXES)[number];
