import { BaseGearAffix } from "./types";

export const TWO_HANDED_SWORD_BASE_AFFIX_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Lucky Critical Strike\n(-40--50)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "Lucky Critical Strike<> ` (-40--50)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Agility Blessing Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Agility Blessing Stacks ` +2` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Focus Blessing Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks ` +2` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Tenacity Blessing Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Tenacity Blessing Stacks ` +2` ",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "Multistrikes deal  (28-32)% increasing damage",
    valueRanges: [],
    rawAffix: "Multistrikes deal ` (28-32)`% increasing damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(10-14)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(10-14)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(12-16)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(12-16)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(48-64)% gear Physical Damage",
    valueRanges: [],
    rawAffix: "` +(48-64)`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(60-64)% chance to Multistrike",
    valueRanges: [],
    rawAffix: "` +(60-64)`% chance to Multistrike",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "Adds  (64-68) -  (80-84) Physical Damage to the gear",
    valueRanges: [],
    rawAffix: "Adds ` (64-68)` - ` (80-84)` Physical Damage to the gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(12-16)% Attack Speed",
    valueRanges: [],
    rawAffix: "` +(12-16)`% Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Erosion Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Melee Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Melee Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(40-48)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(40-48)`% Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (1-3) -  (60-65) Lightning Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (1-3)` - ` (60-65)` Lightning Damage to Attacks",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (24-29) -  (34-39) Cold Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (24-29)` - ` (34-39)` Cold Damage to Attacks",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (24-29) -  (34-39) Fire Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (24-29)` - ` (34-39)` Fire Damage to Attacks",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (25-30) -  (33-38) Physical Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (25-30)` - ` (33-38)` Physical Damage to Attacks",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (26-31) -  (32-37) Erosion Damage to Attacks",
    valueRanges: [],
    rawAffix: "Adds ` (26-31)` - ` (32-37)` Erosion Damage to Attacks",
  },
] as const satisfies readonly BaseGearAffix[];

export type TwoHandedSwordBaseAffixAffix =
  (typeof TWO_HANDED_SWORD_BASE_AFFIX_AFFIXES)[number];
