import { BaseGearAffix } from "./types";

export const TWO_HANDED_HAMMER_TOWER_SEQUENCE_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      " +120% gear Physical Damage\n-20% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix:
      "` +120`% gear Physical Damage<> ` -20`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      " +200% Fearless Aura\n-30% additional Fearless Sealed Mana Compensation",
    valueRanges: [],
    rawAffix:
      "` +200`% Fearless Aura<> ` -30`% additional Fearless Sealed Mana Compensation",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      " +30% additional Deterioration Damage\n10% chance to inflict  2 additional stack(s) of Deterioration",
    valueRanges: [],
    rawAffix:
      "` +30`% additional Deterioration Damage<> ` 10`% chance to inflict ` 2` additional stack(s) of Deterioration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: " +50% Elemental Damage for the gear\n-25% gear Physical Damage",
    valueRanges: [],
    rawAffix:
      "` +50`% Elemental Damage for the gear<> ` -25`% gear Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Adds  1 -  7 Lightning Damage to Attacks per  10 Dexterity",
    valueRanges: [],
    rawAffix:
      "Adds ` 1` - ` 7` Lightning Damage to Attacks per ` 10` Dexterity",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Adds  2 -  2 Physical Damage to Attacks per  2260 Armor",
    valueRanges: [],
    rawAffix: "Adds ` 2` - ` 2` Physical Damage to Attacks per ` 2260` Armor",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "Adds  3 -  5 Fire Damage to Attacks per  10 Strength",
    valueRanges: [],
    rawAffix: "Adds ` 3` - ` 5` Fire Damage to Attacks per ` 10` Strength",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Enemies have a  30% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to  25% of their Max Life to enemies within a  5 m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a ` 30`% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to ` 25`% of their Max Life to enemies within a ` 5` m radius",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Main Skill is supported by Lv.  25 Steamroll\n+25% additional Melee Damage",
    valueRanges: [],
    rawAffix:
      "Main Skill is supported by Lv. ` 25` Steamroll<> ` +25`% additional Melee Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +12% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +12`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +16% all stats",
    valueRanges: [],
    rawAffix: "` +16`% all stats",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +16% additional damage for Weapons",
    valueRanges: [],
    rawAffix: "` +16`% additional damage for Weapons",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +16% Cold Penetration",
    valueRanges: [],
    rawAffix: "` +16`% Cold Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +16% Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +16`% Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +16% Fire Penetration",
    valueRanges: [],
    rawAffix: "` +16`% Fire Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +16% Lightning Penetration",
    valueRanges: [],
    rawAffix: "` +16`% Lightning Penetration",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +20% additional damage on Critical Strike",
    valueRanges: [],
    rawAffix: "` +20`% additional damage on Critical Strike",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +20% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +20`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Hammer",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +8`% gear Attack Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type TwoHandedHammerTowerSequenceAffix =
  (typeof TWO_HANDED_HAMMER_TOWER_SEQUENCE_AFFIXES)[number];
