import { BaseGearAffix } from "./types";

export const TWO_HANDED_SWORD_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " (61-78)% additional damage applied to Life",
    valueRanges: [],
    rawAffix: "` (61-78)`% additional damage applied to Life",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(106-137)% additional damage against Frozen enemies",
    valueRanges: [],
    rawAffix: "` +(106-137)`% additional damage against Frozen enemies",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(110-130)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(110-130)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(251-325)% Demolisher Charge Restoration Speed",
    valueRanges: [],
    rawAffix: "` +(251-325)`% Demolisher Charge Restoration Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(96-120)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(96-120)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +60% Steep Strike chance.\n+(49-62)% additional Steep Strike Damage",
    valueRanges: [],
    rawAffix:
      "` +60`% Steep Strike chance.<> ` +(49-62)`% additional Steep Strike Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Adds  55% of Main-Hand Weapon Damage to Base Ignite Damage",
    valueRanges: [],
    rawAffix: "Adds ` 55`% of Main-Hand Weapon Damage to Base Ignite Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " (43-60)% additional damage applied to Life",
    valueRanges: [],
    rawAffix: "` (43-60)`% additional damage applied to Life",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(176-250)% Demolisher Charge Restoration Speed",
    valueRanges: [],
    rawAffix: "` +(176-250)`% Demolisher Charge Restoration Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(70-90)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(70-90)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(75-105)% additional damage against Frozen enemies",
    valueRanges: [],
    rawAffix: "` +(75-105)`% additional damage against Frozen enemies",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(80-100)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(80-100)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +46% Steep Strike chance.\n+(35-48)% additional Steep Strike Damage",
    valueRanges: [],
    rawAffix:
      "` +46`% Steep Strike chance.<> ` +(35-48)`% additional Steep Strike Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Adds  48% of Main-Hand Weapon Damage to Base Ignite Damage",
    valueRanges: [],
    rawAffix: "Adds ` 48`% of Main-Hand Weapon Damage to Base Ignite Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(120-140)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(120-140)`% Focus Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(145-187)% chance to Multistrike",
    valueRanges: [],
    rawAffix: "` +(145-187)`% chance to Multistrike",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(151-195)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(151-195)`% Affliction Effect",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(181-234)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(328-468)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(328-468)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(51-65)% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +(51-65)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template:
      " +(66-94)% Attack and Cast Speed\n+(66-94)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(66-94)`% Attack and Cast Speed<> ` +(66-94)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(102-144)% chance to Multistrike",
    valueRanges: [],
    rawAffix: "` +(102-144)`% chance to Multistrike",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(106-150)% Affliction Effect",
    valueRanges: [],
    rawAffix: "` +(106-150)`% Affliction Effect",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180)% Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(127-180)`% Critical Strike Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(252-360)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(252-360)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(36-50)% Attack Critical Strike Rating for this gear",
    valueRanges: [],
    rawAffix: "` +(36-50)`% Attack Critical Strike Rating for this gear",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template:
      " +(51-72)% Attack and Cast Speed\n+(51-72)% Minion Attack and Cast Speed",
    valueRanges: [],
    rawAffix:
      "` +(51-72)`% Attack and Cast Speed<> ` +(51-72)`% Minion Attack and Cast Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(90-110)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(90-110)`% Focus Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(217-281)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(217-281)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(217-281)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(217-281)`% Erosion Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(217-281)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(217-281)`% Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(31-39)% Energy Shield Regain",
    valueRanges: [],
    rawAffix: "` +(31-39)`% Energy Shield Regain",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(31-39)% Life Regain",
    valueRanges: [],
    rawAffix: "` +(31-39)`% Life Regain",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(33-42)% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +(33-42)`% gear Attack Speed",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(152-216)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(152-216)`% Elemental Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(152-216)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(152-216)`% Erosion Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(152-216)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(152-216)`% Physical Damage",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(22-30)% Energy Shield Regain",
    valueRanges: [],
    rawAffix: "` +(22-30)`% Energy Shield Regain",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(22-30)% Life Regain",
    valueRanges: [],
    rawAffix: "` +(22-30)`% Life Regain",
  },
  {
    equipmentSlot: "Two-Handed",
    equipmentType: "Two-Handed Sword",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(23-32)% gear Attack Speed",
    valueRanges: [],
    rawAffix: "` +(23-32)`% gear Attack Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type TwoHandedSwordSuffixAffix =
  (typeof TWO_HANDED_SWORD_SUFFIX_AFFIXES)[number];
