import { BaseGearAffix } from "./types";

export const WAND_SUFFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " -15% additional Cast Speed\n+(54-69)% additional Spell Damage",
    valueRanges: [],
    rawAffix:
      "` -15`% additional Cast Speed<> ` +(54-69)`% additional Spell Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(41-52)% chance to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(41-52)`% chance to deal Double Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(48-60)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(48-60)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(54-69)% additional damage against Frozen enemies",
    valueRanges: [],
    rawAffix: "` +(54-69)`% additional damage against Frozen enemies",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +(55-65)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(55-65)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(62-88)% additional Hit Damage for skills cast by Spell Burst",
    valueRanges: [],
    rawAffix:
      "` +(62-88)`% additional Hit Damage for skills cast by Spell Burst",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template:
      " +2 Parabolic Projectile Split Quantity\n+(8-12)% additional Projectile Damage",
    valueRanges: [],
    rawAffix:
      "` +2` Parabolic Projectile Split Quantity<> ` +(8-12)`% additional Projectile Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Terra Quantity  +1 \n+5% additional damage",
    valueRanges: [],
    rawAffix: "Max Terra Quantity ` +1` <> ` +5`% additional damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " -15% additional Cast Speed\n+(38-53)% additional Spell Damage",
    valueRanges: [],
    rawAffix:
      "` -15`% additional Cast Speed<> ` +(38-53)`% additional Spell Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(29-40)% chance to deal Double Damage",
    valueRanges: [],
    rawAffix: "` +(29-40)`% chance to deal Double Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(35-45)% Focus Damage Enhancement",
    valueRanges: [],
    rawAffix: "` +(35-45)`% Focus Damage Enhancement",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(38-53)% additional damage against Frozen enemies",
    valueRanges: [],
    rawAffix: "` +(38-53)`% additional damage against Frozen enemies",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +(40-50)% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least  8 Combo Point(s)",
    valueRanges: [],
    rawAffix:
      "` +(40-50)`% Combo Damage Enhancement if the Combo Finisher cast recently consumes at least ` 8` Combo Point(s)",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(48-68)% additional Hit Damage for skills cast by Spell Burst",
    valueRanges: [],
    rawAffix:
      "` +(48-68)`% additional Hit Damage for skills cast by Spell Burst",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template:
      " +1 Parabolic Projectile Split Quantity\n+(12-16)% additional Projectile Damage",
    valueRanges: [],
    rawAffix:
      "` +1` Parabolic Projectile Split Quantity<> ` +(12-16)`% additional Projectile Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Terra Quantity  +1 \n+1% additional damage",
    valueRanges: [],
    rawAffix: "Max Terra Quantity ` +1` <> ` +1`% additional damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(126-163) Spell Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(126-163)` Spell Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(181-234)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(181-234)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(44-62)% Max Mana",
    valueRanges: [],
    rawAffix: "` +(44-62)`% Max Mana",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(60-70)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(60-70)`% Focus Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117)% Mana Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(91-117)`% Mana Regeneration Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117)% Spell Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(91-117)`% Spell Critical Strike Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(127-180)% Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(127-180)`% Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(34-48)% Max Mana",
    valueRanges: [],
    rawAffix: "` +(34-48)`% Max Mana",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(45-54)% Focus Speed",
    valueRanges: [],
    rawAffix: "` +(45-54)`% Focus Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90)% Mana Regeneration Speed",
    valueRanges: [],
    rawAffix: "` +(64-90)`% Mana Regeneration Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90)% Spell Critical Strike Damage",
    valueRanges: [],
    rawAffix: "` +(64-90)`% Spell Critical Strike Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(89-125) Spell Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +(89-125)` Spell Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Erosion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(19-23)% Energy Shield Regain",
    valueRanges: [],
    rawAffix: "` +(19-23)`% Energy Shield Regain",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(19-23)% Life Regain",
    valueRanges: [],
    rawAffix: "` +(19-23)`% Life Regain",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(34-47)% Cast Speed\n+(34-47)% Minion Cast Speed",
    valueRanges: [],
    rawAffix: "` +(34-47)`% Cast Speed<> ` +(34-47)`% Minion Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(50-64)% Spell Burst Charge Speed",
    valueRanges: [],
    rawAffix: "` +(50-64)`% Spell Burst Charge Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(14-18)% Energy Shield Regain",
    valueRanges: [],
    rawAffix: "` +(14-18)`% Energy Shield Regain",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(14-18)% Life Regain",
    valueRanges: [],
    rawAffix: "` +(14-18)`% Life Regain",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(26-36)% Cast Speed\n+(26-36)% Minion Cast Speed",
    valueRanges: [],
    rawAffix: "` +(26-36)`% Cast Speed<> ` +(26-36)`% Minion Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(38-47)% Spell Burst Charge Speed",
    valueRanges: [],
    rawAffix: "` +(38-47)`% Spell Burst Charge Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Erosion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(78-108)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(78-108)`% Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Suffix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(78-108)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(78-108)`% Physical Damage",
  },
] as const satisfies readonly BaseGearAffix[];

export type WandSuffixAffix = (typeof WAND_SUFFIX_AFFIXES)[number];
