import { BaseGearAffix } from "./types";

export const WAND_TOWER_SEQUENCE_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    craftableAffix:
      "+120% Spell Amplification Aura<> -20% additional Spell Amplification Sealed Mana Compensation",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    craftableAffix:
      "+15% additional Deterioration Damage<> 10% chance to inflict 1additional stack(s) of Deterioration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    craftableAffix: "+25% additional Hit Damage for skills cast by Spell Burst",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    craftableAffix: "+35% additional damage<> -10% additional Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    craftableAffix:
      "Adds 200- 220Cold Damage to Spells when having at least 800Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    craftableAffix:
      "Enemies have a 15% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to 25% of their Max Life to enemies within a 5m radius",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    craftableAffix:
      "Max Tenacity Blessing Stacks -1<> Max Focus Blessing Stacks +1<> Max Agility Blessing Stacks +1",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    craftableAffix: "The Main Skill is supported by Lv. 25Control Spell",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    craftableAffix: "+10% additional damage on Critical Strike",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    craftableAffix: "+16% Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    craftableAffix: "+55Spell Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    craftableAffix: "+6% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    craftableAffix: "+8% all stats",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    craftableAffix: "+8% additional Spell Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    craftableAffix: "+8% Cold Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    craftableAffix: "+8% Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    craftableAffix: "+8% Fire Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    craftableAffix: "+8% Lightning Penetration",
  },
] as const satisfies readonly BaseGearAffix[];

export type WandTowerSequenceAffix =
  (typeof WAND_TOWER_SEQUENCE_AFFIXES)[number];
