import { BaseGearAffix } from "./types";

export const WAND_TOWER_SEQUENCE_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      " +120% Spell Amplification Aura\n-20% additional Spell Amplification Sealed Mana Compensation",
    valueRanges: [],
    rawAffix:
      "` +120`% Spell Amplification Aura<> ` -20`% additional Spell Amplification Sealed Mana Compensation",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      " +15% additional Deterioration Damage\n10% chance to inflict  1 additional stack(s) of Deterioration",
    valueRanges: [],
    rawAffix:
      "` +15`% additional Deterioration Damage<> ` 10`% chance to inflict ` 1` additional stack(s) of Deterioration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: " +25% additional Hit Damage for skills cast by Spell Burst",
    valueRanges: [],
    rawAffix: "` +25`% additional Hit Damage for skills cast by Spell Burst",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: " +35% additional damage\n-10% additional Cast Speed",
    valueRanges: [],
    rawAffix: "` +35`% additional damage<> ` -10`% additional Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Adds  200 -  220 Cold Damage to Spells when having at least  800 Intelligence",
    valueRanges: [],
    rawAffix:
      "Adds ` 200` - ` 220` Cold Damage to Spells when having at least ` 800` Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Enemies have a  15% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to  25% of their Max Life to enemies within a  5 m radius",
    valueRanges: [],
    rawAffix:
      "Enemies have a ` 15`% chance to explode when defeated by an Attack or Spell, dealing Secondary Physical Damage equal to ` 25`% of their Max Life to enemies within a ` 5` m radius",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template:
      "Max Tenacity Blessing Stacks  -1 \nMax Focus Blessing Stacks  +1 \nMax Agility Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix:
      "Max Tenacity Blessing Stacks ` -1` <> Max Focus Blessing Stacks ` +1` <> Max Agility Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Advanced",
    tier: "",
    template: "The Main Skill is supported by Lv.  25 Control Spell",
    valueRanges: [],
    rawAffix: "The Main Skill is supported by Lv. ` 25` Control Spell",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +10% additional damage on Critical Strike",
    valueRanges: [],
    rawAffix: "` +10`% additional damage on Critical Strike",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +16% Cast Speed",
    valueRanges: [],
    rawAffix: "` +16`% Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +55 Spell Critical Strike Rating",
    valueRanges: [],
    rawAffix: "` +55` Spell Critical Strike Rating",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +6% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +6`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% all stats",
    valueRanges: [],
    rawAffix: "` +8`% all stats",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% additional Spell Damage",
    valueRanges: [],
    rawAffix: "` +8`% additional Spell Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% Cold Penetration",
    valueRanges: [],
    rawAffix: "` +8`% Cold Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +8`% Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% Fire Penetration",
    valueRanges: [],
    rawAffix: "` +8`% Fire Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Tower Sequence",
    craftingPool: "Intermediate",
    tier: "",
    template: " +8% Lightning Penetration",
    valueRanges: [],
    rawAffix: "` +8`% Lightning Penetration",
  },
] as const satisfies readonly BaseGearAffix[];

export type WandTowerSequenceAffix =
  (typeof WAND_TOWER_SEQUENCE_AFFIXES)[number];
