import { BaseGearAffix } from "./types";

export const WAND_PREFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(26-36)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(26-36)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(28-39)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(28-39)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +(3-4) Spell Skill Level",
    valueRanges: [],
    rawAffix: "` +(3-4)` Spell Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: " +2 Jumps\n+(12-16)% additional damage",
    valueRanges: [],
    rawAffix: "` +2` Jumps<> ` +(12-16)`% additional damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "0",
    template: "Max Terra Charge Stacks  +3 ",
    valueRanges: [],
    rawAffix: "Max Terra Charge Stacks ` +3` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(18-25)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(18-25)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +(22-30)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(22-30)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +2 Jumps\n+(8-10)% additional damage",
    valueRanges: [],
    rawAffix: "` +2` Jumps<> ` +(8-10)`% additional damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: " +3 Spell Skill Level",
    valueRanges: [],
    rawAffix: "` +3` Spell Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Ultimate",
    tier: "1",
    template: "Max Terra Charge Stacks  +2 ",
    valueRanges: [],
    rawAffix: "Max Terra Charge Stacks ` +2` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(2-3) Cold Skill Level",
    valueRanges: [],
    rawAffix: "` +(2-3)` Cold Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(2-3) Erosion Skill Level",
    valueRanges: [],
    rawAffix: "` +(2-3)` Erosion Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(2-3) Fire Skill Level",
    valueRanges: [],
    rawAffix: "` +(2-3)` Fire Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(2-3) Lightning Skill Level",
    valueRanges: [],
    rawAffix: "` +(2-3)` Lightning Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(2-3) Physical Skill Level",
    valueRanges: [],
    rawAffix: "` +(2-3)` Physical Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Dexterity",
    valueRanges: [],
    rawAffix: "` +(91-117)` Dexterity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Intelligence",
    valueRanges: [],
    rawAffix: "` +(91-117)` Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "0",
    template: " +(91-117) Strength",
    valueRanges: [],
    rawAffix: "` +(91-117)` Strength",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Dexterity",
    valueRanges: [],
    rawAffix: "` +(64-90)` Dexterity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Intelligence",
    valueRanges: [],
    rawAffix: "` +(64-90)` Intelligence",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +(64-90) Strength",
    valueRanges: [],
    rawAffix: "` +(64-90)` Strength",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +2 Cold Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Cold Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +2 Erosion Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Erosion Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +2 Fire Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Fire Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +2 Lightning Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Lightning Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Advanced",
    tier: "1",
    template: " +2 Physical Skill Level",
    valueRanges: [],
    rawAffix: "` +2` Physical Skill Level",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(109-140)% Spell Damage",
    valueRanges: [],
    rawAffix: "` +(109-140)`% Spell Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: " +(181-234) Max Mana",
    valueRanges: [],
    rawAffix: "` +(181-234)` Max Mana",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (82-84) -  (106-113) Fire Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (82-84)` - ` (106-113)` Fire Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (83-85) -  (110-112) Cold Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (83-85)` - ` (110-112)` Cold Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (87-89) -  (106-108) Erosion Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (87-89)` - ` (106-108)` Erosion Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (87-89) -  (106-108) Physical Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (87-89)` - ` (106-108)` Physical Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "0",
    template: "Adds  (9-11) -  (184-186) Lightning Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (9-11)` - ` (184-186)` Lightning Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(127-180) Max Mana",
    valueRanges: [],
    rawAffix: "` +(127-180)` Max Mana",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: " +(77-108)% Spell Damage",
    valueRanges: [],
    rawAffix: "` +(77-108)`% Spell Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (63-65) -  (82-87) Fire Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (63-65)` - ` (82-87)` Fire Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (64-66) -  (85-87) Cold Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (64-66)` - ` (85-87)` Cold Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (67-69) -  (82-84) Erosion Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (67-69)` - ` (82-84)` Erosion Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (67-69) -  (82-84) Physical Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (67-69)` - ` (82-84)` Physical Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Prefix",
    craftingPool: "Basic",
    tier: "1",
    template: "Adds  (7-9) -  (142-144) Lightning Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (7-9)` - ` (142-144)` Lightning Damage to Spells",
  },
] as const satisfies readonly BaseGearAffix[];

export type WandPrefixAffix = (typeof WAND_PREFIX_AFFIXES)[number];
