import { BaseGearAffix } from "./types";

export const WAND_BASE_AFFIX_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Agility Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Agility Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Focus Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Focus Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "0",
    template: "Max Tenacity Blessing Stacks  +1 ",
    valueRanges: [],
    rawAffix: "Max Tenacity Blessing Stacks ` +1` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(5-7)% Armor DMG Mitigation Penetration",
    valueRanges: [],
    rawAffix: "` +(5-7)`% Armor DMG Mitigation Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +(6-8)% Elemental and Erosion Resistance Penetration",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Elemental and Erosion Resistance Penetration",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: " +1 Parabolic Projectile Split Quantity",
    valueRanges: [],
    rawAffix: "` +1` Parabolic Projectile Split Quantity",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "1",
    template: "Projectile Quantity  +1 ",
    valueRanges: [],
    rawAffix: "Projectile Quantity ` +1` ",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Elemental Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Elemental Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Erosion Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Erosion Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Physical Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Physical Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(20-24)% Spell Damage",
    valueRanges: [],
    rawAffix: "` +(20-24)`% Spell Damage",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: " +(6-8)% Cast Speed",
    valueRanges: [],
    rawAffix: "` +(6-8)`% Cast Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (1-2) -  (28-32) Lightning Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (1-2)` - ` (28-32)` Lightning Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (10-13) -  (14-19) Cold Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (10-13)` - ` (14-19)` Cold Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (10-13) -  (14-19) Physical Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (10-13)` - ` (14-19)` Physical Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (11-13) -  (15-18) Erosion Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (11-13)` - ` (15-18)` Erosion Damage to Spells",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Affix",
    craftingPool: "",
    tier: "2",
    template: "Adds  (9-14) -  (15-20) Fire Damage to Spells",
    valueRanges: [],
    rawAffix: "Adds ` (9-14)` - ` (15-20)` Fire Damage to Spells",
  },
] as const satisfies readonly BaseGearAffix[];

export type WandBaseAffixAffix = (typeof WAND_BASE_AFFIX_AFFIXES)[number];
