import { BaseGearAffix } from "./types";

export const WAND_BASE_STATS_AFFIXES = [
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
  {
    equipmentSlot: "One-Handed",
    equipmentType: "Wand",
    affixType: "Base Stats",
    craftingPool: "",
    tier: "",
    craftableAffix: "500Critical Strike Rating<> 1.2Attack Speed",
  },
] as const satisfies readonly BaseGearAffix[];

export type WandBaseStatsAffix = (typeof WAND_BASE_STATS_AFFIXES)[number];
